In [48]:
#5
function PoliCuad(a,b,c)
    if b^2 - 4a*c >= 0 #En caso de que el discriminante sea mayor o igual a 0 se usa la formula general normal.
        x = zeros(2,1) #Ponemos un arreglo donde poner los datos.
        #Como es raíz tiene 2 resultados, + o -
        x[1,1] += (-b+sqrt((b^2) - 4a*c))/2a
        x[2,1] += (-b-sqrt((b^2) - 4a*c))/2a
    elseif b^2 - 4a*c < 0 #Si el discriminante es menor a 0 hacemos unos ajustes para obtener el resultado en complejos.
        x = zeros(Complex{Float64},2,1) #En este caso definimos un arreglo en complejos para no tener problemas.
        #al ser el discriminante 
        x[1,1] += (-b+(sqrt(complex(b^2 - 4a*c))))/2a #Caso para x1
        x[2,1] += (-b-(sqrt(complex(b^2 - 4a*c))))/2a #Caso para x2
    end
    x
end

PoliCuad (generic function with 1 method)

In [49]:
PoliCuad(9,24,16)

2×1 Array{Float64,2}:
 -1.33333
 -1.33333

In [50]:
PoliCuad(1,2,0)

2×1 Array{Float64,2}:
  0.0
 -2.0

In [51]:
PoliCuad(50,2,4)

2×1 Array{Complex{Float64},2}:
 -0.02+0.282135im
 -0.02-0.282135im