In [5]:
function SumaMatr2X2(A,B)
    if size(A)==(2, 2);size(B)==(2, 2)
        C=zeros(size(A))
        for i ∈ 1:size(A)[1]
            for j ∈ 1:size(A)[2]
                b=A[i,j]+B[i,j]
                C[i,j]+=b
            end
        end
        C
    else
        print("Nel")
    end
end

SumaMatr2X2 (generic function with 1 method)

In [6]:
A = [2 3; 4 5; 3 1]

3×2 Array{Int64,2}:
 2  3
 4  5
 3  1

In [7]:
B = [5 7 ; 4 2; 2 3]

3×2 Array{Int64,2}:
 5  7
 4  2
 2  3

In [8]:
size(A)

(3, 2)

In [9]:
zeros(size(A))

3×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [10]:
SumaMatr2X2(A,B)

Nel

In [11]:
size(A)

(3, 2)

In [12]:
A=[2 3; 4 5]

2×2 Array{Int64,2}:
 2  3
 4  5

In [13]:
B=[5 7 ; 4 2]

2×2 Array{Int64,2}:
 5  7
 4  2

In [14]:
SumaMatr2X2(A,B)

2×2 Array{Float64,2}:
 7.0  10.0
 8.0   7.0

In [15]:
function SumaMatr(A,B)
    if size(A)==size(B)
        C=zeros(size(A))
        for i ∈ 1:size(A)[1]
            for j ∈ 1:size(A)[2]
                b=A[i,j]+B[i,j]
                C[i,j]+=b
            end
        end
        C
    else
        print("Nel")
    end
end

SumaMatr (generic function with 1 method)

In [16]:
A = [2 3 4; 4 5 0; 3 1 8]

3×3 Array{Int64,2}:
 2  3  4
 4  5  0
 3  1  8

In [17]:
B = [4 5 2; 3 2 1; 9 7 2]

3×3 Array{Int64,2}:
 4  5  2
 3  2  1
 9  7  2

In [18]:
SumaMatr(A,B)

3×3 Array{Float64,2}:
  6.0  8.0   6.0
  7.0  7.0   1.0
 12.0  8.0  10.0