<div class="alert alert-info" role="alert">
<p class ="lead"> 
<h1>Suma de Matrices </h1>
<h2> Computación </h2>
<h2>Física, Facultad de Ciencias. UNAM </h2>
<h3>Celeste Castro Granados</h3>
</div>

a) Vamos a escribir un programa que nos permita sumar dos matrices en $ ℝ^{2x2} $ en el cual el usuario será el que definirá cada entrada de las matrices.

Sean dos matrices $ A,B \in m_{2x2} $, la suma de dos matrices está dada de la siguiente manera:

$$ A_{2x2}+B_{2x2} = 
\begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\\end{pmatrix} 
+
\begin{pmatrix}
b_{11} & b_{12}\\
b_{21} & b_{22}\\\end{pmatrix}=... $$ 

$$
...=\begin{pmatrix}
a_{11}+b_{11} & a_{12}+b_{12}\\
    a_{21}+b_{21} & a_{22}+b_{22}\\\end{pmatrix}=C_{2x2} $$

Para empezar vamos a definir los renglones i, j y un ciclo for que contenga a otro dentro de este para que recorra todos los componentes de la matriz.

In [1]:
function SumMat(A,B)
    n=size(A) #Definimos n del tamaño de la matriz A
    
    if n !=size(B)
        println("Las matrices deben ser de la misma dimensión") #Esto va a suceder cuando las matrices no sean del mismo tamaño, no se va a realizar la operación
    else
        C=zeros(A) #Esta va a ser nuestra matriz resultante 
        i=1
        j=1
        for h ∈ 1:2 #Va a ir de 1 hasta 2 porque son matrices cuadradas
            for m ∈ 1:2
            C[i,j]=A[i,j]+B[i,j] #Decimos que la entrada i,j de C va a ser igual a la suma de la misma entrada en A + la misma entrada en B
            i=i+1 #Aquí le decimos que vaya recorriendo renglón por renglón
            end
            i=1
            j=j+1
        end
        C
    end
end      

SumMat (generic function with 1 method)

Una vez definida nuestra función, vamos a probarla con matrices aleatorias:

In [2]:
A = rand(2,2)

2×2 Array{Float64,2}:
 0.318539  0.157457
 0.626308  0.453926

In [3]:
B = rand(2,2)

2×2 Array{Float64,2}:
 0.716896  0.353618
 0.300358  0.444424

In [4]:
SumMat(A,B)

2×2 Array{Float64,2}:
 1.03543   0.511075
 0.926666  0.89835 

Otro ejemplo:

In [5]:
A=hcat([2,3],[5,7])

2×2 Array{Int64,2}:
 2  5
 3  7

In [6]:
B=hcat([4,2],[8,5])

2×2 Array{Int64,2}:
 4  8
 2  5

In [7]:
SumMat(A,B)

2×2 Array{Int64,2}:
 6  13
 5  12

Y un último ejemplo:

In [8]:
A =hcat([2,3],[5,7],[9,1])

2×3 Array{Int64,2}:
 2  5  9
 3  7  1

In [9]:
B=hcat([2,11],[5,3])

2×2 Array{Int64,2}:
  2  5
 11  3

In [10]:
SumMat(A,B)

Las matrices deben ser de la misma dimensión


Y aquí observamos lo que sucede cuando las matrices no son de la misma dimensión.

**b) Para el caso generalizado definimos los renglones i, j y un ciclo for que considere las dimesiones de las matrices para repetirse i o j veces, este contendra a otro dentro ciclo for para que recorra todos los componentes de la matriz.**


In [11]:
function SumaMat(A,B)
    n=size(A)
    
    if n !=size(B)
        println("Las matrices deben de ser de la misma dimensión")
    else
        C=zeros(A)
        i=1
        j=1
        for h ∈ 1:n[2]
            for m ∈ 1:n[1]
            C[i,j]=A[i,j]+B[i,j]
            i=i+1
            end
            i=1
            j=j+1
        end
        C
    end
end      

SumaMat (generic function with 1 method)

Ahora lo que vamos a hacer es probarlo con un ejemplo, en donde las entradas de las matrices se van a leer de un archivo, y posteriormente realizaremos la suma entre ellas.

Vamos a usar dos archivo llamados "numeros.csv" y "numeros3.csv", de los cuales obtendremos nuestros datos.

In [12]:
Matriz1 = readdlm("numeros.csv",'|')

10×5 Array{Float64,2}:
 0.279112   0.603476    0.174542   0.949193   0.0184632
 0.491553   0.429904    0.54561    0.0450827  0.240349 
 0.423377   0.00218974  0.746105   0.672648   0.627589 
 0.818008   0.876047    0.924085   0.614007   0.0527286
 0.380846   0.0353204   0.926518   0.0885945  0.822851 
 0.0299714  0.762       0.503472   0.568603   0.45383  
 0.113166   0.925569    0.0800565  0.604007   0.257965 
 0.803592   0.186209    0.416348   0.568096   0.954342 
 0.795183   0.860483    0.069683   0.60982    0.921001 
 0.667658   0.849752    0.793487   0.396402   0.926119 

In [13]:
Matriz2 = readdlm("numeros3.csv",'|')

10×5 Array{Float64,2}:
 0.377741    0.193747  0.748039    0.29462   0.383843 
 0.92103     0.797538  0.331989    0.641476  0.557273 
 0.883586    0.300195  0.437535    0.993535  0.619089 
 0.475396    0.45006   0.00652487  0.890546  0.0529748
 0.319692    0.883792  0.247058    0.715374  0.185885 
 0.731463    0.390556  0.616334    0.511008  0.603723 
 0.827293    0.864427  0.043315    0.583696  0.33245  
 0.882397    0.622723  0.466879    0.563903  0.0119117
 0.0944181   0.306642  0.982249    0.611868  0.0324575
 0.00512328  0.891741  0.19596     0.174805  0.632789 

Y finalmente procedemos a sumar nuestras dos matrices que vamos a definir como A y B mediante nuestra función.

In [14]:
A = Matriz1

10×5 Array{Float64,2}:
 0.279112   0.603476    0.174542   0.949193   0.0184632
 0.491553   0.429904    0.54561    0.0450827  0.240349 
 0.423377   0.00218974  0.746105   0.672648   0.627589 
 0.818008   0.876047    0.924085   0.614007   0.0527286
 0.380846   0.0353204   0.926518   0.0885945  0.822851 
 0.0299714  0.762       0.503472   0.568603   0.45383  
 0.113166   0.925569    0.0800565  0.604007   0.257965 
 0.803592   0.186209    0.416348   0.568096   0.954342 
 0.795183   0.860483    0.069683   0.60982    0.921001 
 0.667658   0.849752    0.793487   0.396402   0.926119 

In [15]:
B = Matriz2

10×5 Array{Float64,2}:
 0.377741    0.193747  0.748039    0.29462   0.383843 
 0.92103     0.797538  0.331989    0.641476  0.557273 
 0.883586    0.300195  0.437535    0.993535  0.619089 
 0.475396    0.45006   0.00652487  0.890546  0.0529748
 0.319692    0.883792  0.247058    0.715374  0.185885 
 0.731463    0.390556  0.616334    0.511008  0.603723 
 0.827293    0.864427  0.043315    0.583696  0.33245  
 0.882397    0.622723  0.466879    0.563903  0.0119117
 0.0944181   0.306642  0.982249    0.611868  0.0324575
 0.00512328  0.891741  0.19596     0.174805  0.632789 

In [16]:
SumaMat(A,B)

10×5 Array{Float64,2}:
 0.656853  0.797223  0.922581  1.24381   0.402306
 1.41258   1.22744   0.877599  0.686559  0.797622
 1.30696   0.302385  1.18364   1.66618   1.24668 
 1.2934    1.32611   0.93061   1.50455   0.105703
 0.700537  0.919112  1.17358   0.803968  1.00874 
 0.761434  1.15256   1.11981   1.07961   1.05755 
 0.940459  1.79      0.123371  1.1877    0.590415
 1.68599   0.808932  0.883228  1.132     0.966254
 0.889601  1.16713   1.05193   1.22169   0.953458
 0.672781  1.74149   0.989447  0.571207  1.55891 