In [16]:
function MatVec(A,v)
    if size(A)[2] == length(v) #Aquí le pedimos que el tamaño del vector columna sea igual al tamaño del renglón de la matriz
        r = zeros(size(A)[1]) #Aquí creamos un areglo de ceros del tamaño de las columnas de A en la que alojaremos el resultado
        for i in 1:size(A)[1] #Aquí especificamos que las operaciones a realizar son elemento a elemento de las columnas de A
            k=0 #Aquí creamos una entrada que ira alojando cada elemento de r
            for j in 1:size(A)[2] #Aquí hacemos referencia a cada elemento de los renglones de A sobre los que se aplicaran las siguientes operaciones 
                m=A[i,j]*v[j] #Aquí efectuamos las operaciones multiplicando el ijesimo elmento de A con el jesimo elemento de v
                k+=m #Le sumamos m a la entrada para que la vaya guardando 
            end
            r[i] = k #el i esimo elemento de r es k, esto es, que k guarda cada elemento de r y lo deposita en r
        end
        r #Aquí pedimos que nos regrese r
    end
end          

MatVec (generic function with 1 method)

In [22]:
A= [1 2 3; 3 4 5; 5 6 7]
v=[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [23]:
size(A)[2]

3

In [24]:
MatVec(A,v)

3-element Array{Float64,1}:
 14.0
 26.0
 38.0

In [52]:
function ProdMatr(A,B)
    if size(A)[2]== size(B)[1] #Aquí le pedimos que las el numero de columnas de A sea el mismo que de renglones en B
        M= zeros(size(A)[1],size(B)[2]) #Aquí creamos un arreglo del tamaño de los renglones de A y las columnas de B
        for i ∈ 1:size(A)[1] #Decimos que para cada elemento en los renglones de A se aplicara qur r=1
            r=1 #r representará el numero de columnas de B
            while r<=size(A)[1] #Decimos que mientras r sea menor o igual al tamaño de los renglones de A ocurrira que p=0
                p=0 #p será el contador que vaya guardando los valores que se acumulen de cada operación para depositarlos en su lugar en la matriz resultante
                for j ∈ 1:size(B)[1] #Decimos que para elemento en los renglones de B ocurriran las siguientes operaciones
                    a=A[i,j]*B[j,r] #Aquí decimos que multiplicaremos el ij esimo elemento de A con el jr esimo elemento de B
                    p+=a #Aquí se suman los resultados que se obtienen de a
                end
                M[i,r]=p #Aquí se declara que p representa cada ir esimo elemento de la matriz resultante
                r+=1 #Aquí se suma a la r una unidad para continuar con el ciclo 
            end
        end
        M #Aquí se pide que imprima M como resultado
    else
        print("Matrices no se pueden multiplicar") #Aquí se pide que se arroje esta respuesta si no se puede efectuar la operación por la diferencia de dimensiones.
    end
end

ProdMatr (generic function with 1 method)

In [53]:
A= [1 2 3; 3 4 5; 5 6 7]
B= [2 4 5; 6 7 8; 6 7 9]

3×3 Array{Int64,2}:
 2  4  5
 6  7  8
 6  7  9

In [54]:
ProdMatr(A,B)

3×3 Array{Float64,2}:
 32.0   39.0   48.0
 60.0   75.0   92.0
 88.0  111.0  136.0