<div class="alert alert-success" role="alert">
 <h1>Producto de una matriz por un vector</h1>
 <h2>Computación</h2>
 <h2>Física, Facultad de Ciencias. UNAM </h2>
 <h3>Celeste Castro Granados</h3>
 </div>

Vamos a crear una función que sea capaz de multiplicar una matriz, que sea introducida por el usuario, por un vector igualmente introducido por el usuario.

Lo primero que tenemos que checar es que efectivamente se pueda llevar a cabo la multiplicación, es decir, concuerden en tamaño los renglones de la matriz con el vector.

Definimos entonces nuestra función, pero para hacerlo, tenemos que definir una función previa que realice el producto interior entre 2 vectores:

In [1]:
function ProductoInt(u,v)
    if length(u) == length(v) #Con esta línea nos aseguramos de que se efectúe sólo si los vectores son de la misma dimensión
        p=0
        for i in eachindex(u) #Aquí nos referimos a que el contador pase por cada índice del vector u
            p = p +u[i]*v[i] #El producto va a ser igual a su valor anterior más el producto de la entrada i tanto en v como en u
        end
        p
    else
        println("u y v deben de ser del mismo tamaño") #Esto va a imprimir en caso de que los vectores no sean de la misma dimensión
    end
end

ProductoInt (generic function with 1 method)

Ya que tenemos la del producto interior, ahora sí, ya podemos establecer la función para multiplicar una matriz por un vector:

In [2]:
function matXvec(A,v)
    if size(A)[2] == length(v) #En esta línea lo que se asegura es que el tamaño de los renglones de A sea igual al del vector v para que se pueda efectuar la multiplicación
        vectorResultante = zeros(size(A)[1]) #Tenemos que el vector que nos va a dar como resultado va a ser del mismo tamaño que las columnas de A 
        for renglon in 1:size(A)[1] #Aquí ya especificamos que va a ir desde 1 hasta cumplir el tamaño de la columna de A 
            vectorResultante[renglon] = ProductoInt(A[renglon,:],v) #Aquí se efectúa la operación usando la función del producto punto 
        end
        vectorResultante #Nos va a dar nuestro vector resultante
    end
end   

matXvec (generic function with 1 method)

Y finalmente, vamos a probar nuestra función definiendo aleatoriamente una matriz y un vector:

In [3]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.399724  0.77772    0.156082
 0.385538  0.0850214  0.993187
 0.119852  0.982208   0.247149

In [4]:
v = rand(3)

3-element Array{Float64,1}:
 0.527466
 0.294557
 0.673536

In [5]:
matXvec(A,v)

3-element Array{Float64,1}:
 0.54505 
 0.897349
 0.518998