a) Crear un archivo con los datos de un movimiento rectilíneo uniforme en el intervalo de tiempo definido por el usuario

In [1]:
function mru(s0,v0,t0,tf,Δt)
    t = collect(t0:Δt:tf)               # definimos el array del tiempo segun el usuario lo define
    s = zeros(t)                        # array de ceros del tamaño de t
    for i in eachindex(t)               # contador que corre por todos los elementos de t
        s[i] = v0*t[i] + s0             # realizamos la expresión del mru para cada punto de t obteniendo su variable correspondiete s
    end
    variables = hcat(t,s)                # concatenamos los datos para escribirlos
    writedlm("mru.csv", variables, '|')  # lo escribimos a mru.csv con | como separador
end

mru (generic function with 1 method)

In [2]:
mru(0,1,0,1,0.01)

Ahora podemos leer el archivo

In [3]:
readdlm("mru.csv", '|')

101×2 Array{Float64,2}:
 0.0   0.0 
 0.01  0.01
 0.02  0.02
 0.03  0.03
 0.04  0.04
 0.05  0.05
 0.06  0.06
 0.07  0.07
 0.08  0.08
 0.09  0.09
 0.1   0.1 
 0.11  0.11
 0.12  0.12
 ⋮         
 0.89  0.89
 0.9   0.9 
 0.91  0.91
 0.92  0.92
 0.93  0.93
 0.94  0.94
 0.95  0.95
 0.96  0.96
 0.97  0.97
 0.98  0.98
 0.99  0.99
 1.0   1.0 

b) Crear un archivo con los datos de un movimiento uniformemente acelerado en un intervalo de tiempo especificado por el usuario

In [4]:
function mua(s0,v0,a,t0,tf,Δt)
    t = collect(t0:Δt:tf)
    s = zeros(t)
    for i in eachindex(t)
        s[i] = v0*t[i] + s0 + 0.5*a*t[i]^2
    end
    variables = hcat(t,s)
    writedlm("mua.csv", variables, '|')
end

mua (generic function with 1 method)

In [5]:
mua(0,50,-9.81,0,11,0.125)

In [6]:
readdlm("mua.csv", '|')

89×2 Array{Float64,2}:
  0.0      0.0    
  0.125    6.17336
  0.25    12.1934 
  0.375   18.0602 
  0.5     23.7737 
  0.625   29.334  
  0.75    34.7409 
  0.875   39.9946 
  1.0     45.095  
  1.125   50.0421 
  1.25    54.8359 
  1.375   59.4765 
  1.5     63.9637 
  ⋮               
  9.625   26.8477 
  9.75    21.2184 
  9.875   15.4359 
 10.0      9.5    
 10.125    3.41086
 10.25    -2.83156
 10.375   -9.22727
 10.5    -15.7763 
 10.625  -22.4785 
 10.75   -29.3341 
 10.875  -36.3429 
 11.0    -43.505  

c) Crear un archivo de datos de tiro parabólico.

In [7]:
function tp(x0,y0,v0,θ,t0,tf,Δt)
    t = collect(t0:Δt:tf)
    x = zeros(t)
    y = zeros(t)
    for i in eachindex(t)
        x[i] = x0 + v0*cos(θ)*t[i]
        y[i] = y0 + v0*sin(θ)*t[i] - 0.5*9.81*t[i]^2
    end
    variables = hcat(t,x,y)
    writedlm("tp.csv", variables, '|')
end

tp (generic function with 1 method)

In [8]:
tp(0,0,100,π/4,0,15,0.125)

In [9]:
readdlm("tp.csv", '|')

121×3 Array{Float64,2}:
  0.0       0.0        0.0    
  0.125     8.83883    8.76219
  0.25     17.6777    17.3711 
  0.375    26.5165    25.8267 
  0.5      35.3553    34.1291 
  0.625    44.1942    42.2782 
  0.75     53.033     50.2739 
  0.875    61.8718    58.1165 
  1.0      70.7107    65.8057 
  1.125    79.5495    73.3416 
  1.25     88.3883    80.7243 
  1.375    97.2272    87.9537 
  1.5     106.066     95.0298 
  ⋮                           
 13.625   963.433     52.8657 
 13.75    972.272     44.9203 
 13.875   981.111     36.8215 
 14.0     989.949     28.5695 
 14.125   998.788     20.1642 
 14.25   1007.63      11.6056 
 14.375  1016.47       2.89373
 14.5    1025.3       -5.97142
 14.625  1034.14     -14.9898 
 14.75   1042.98     -24.1616 
 14.875  1051.82     -33.4866 
 15.0    1060.66     -42.9648 