<div class="alert alert-success" role="alert">
 <h1> Pregunta 7</h1>
 <h2>Computación</h2>
 <h2>Física, Facultad de Ciencias. UNAM </h2>
 <h3>Fernanda Martínez Saldaña</h3>
 </div>

a) Este programa suma dos vectores en $R^3$ insertados por el usuario  

Declaramos des vectores

In [6]:
A=[2,3,3]
B=[8,7,6]

3-element Array{Int64,1}:
 8
 7
 6

In [9]:
function sumavector(A,B) #Generamos una función de suma de vectores
    S=[A[1]+B[1],A[2]+B[2],A[3]+B[3]]  #Introducimos el orden de los vectores en el que deben ser sumados
    print("La suma de los vectores A y B es: $S")  #Imprimimos resultado
end      #Terminamos función

sumavector (generic function with 1 method)

In [10]:
sumavector(A,B)

La suma de los vectores A y B es: [10, 10, 9]

b) Este programa suma dos vectores en $R^n$ leídos de un archivo de datos

Introducimos los vectores

In [33]:
A=[7,3,4]
B=[4,8,7]

3-element Array{Int64,1}:
 4
 8
 7

In [34]:
Creamos un archivo llamado vectorA.csv con writedlm

LoadError: syntax: extra token "un" after end of expression

In [35]:
writedlm("vectorA.csv", A, '|')

Creamos un archivo llamado vectorB.csv con writedlm

In [36]:
writedlm("vectorB.csv", B, '|')

Con cat podemos ver los datos que fueron introducidos

In [37]:
;cat vectorA.csv

7
3
4


In [38]:
;cat vectorB.csv

4
8
7


In [39]:
Con read podemos los datos que fueron introducidos

LoadError: syntax: extra token "read" after end of expression

In [40]:
u = readdlm("vectorA.csv", '|')

3×1 Array{Float64,2}:
 7.0
 3.0
 4.0

In [41]:
v = readdlm("vectorB.csv", '|')

3×1 Array{Float64,2}:
 4.0
 8.0
 7.0

Posteriromente creamos una función que sume dos vectores

In [42]:
function  sumaRn( u , v )   #Generamos una función suma
    if  length(u) ==  length(v)  #Ytilizamos if para decir que la función se puede cumplir si la longitud del vector u es igual a la longitud del vector v 
        S  = zeros(u)     #Empezamos la suma en 0
        for i ∈ eachindex(u)   #Varía la variable i 
           S[i]=u[i]+v[i]    #Sumamos el vector u con v
            end           #Terminamos ciclo for
        print("La suma de los vectores es: $S")  #Imprimimos resultado
        else      #Utilizamos else por si if no se cumple
        print("¡Error! Distintas dimensiones!") #Sei mprime resultado
    end     #Terminamos if
end       #Terminamos función


sumaRn (generic function with 1 method)

Probamos la función suma

In [43]:
sumaRn(u,v)

La suma de los vectores es: [11.0; 11.0; 11.0]

Un ejemplo con vectores de distintas dimensiones:

In [44]:
A=[2,1]

2-element Array{Int64,1}:
 2
 1

In [45]:
B=[4,5,6]


3-element Array{Int64,1}:
 4
 5
 6

In [46]:
writedlm("vectorA.csv", A, '|')


In [47]:
writedlm("vectorB.csv", B, '|')


In [48]:
u = readdlm("vectorA.csv", '|')

2×1 Array{Float64,2}:
 2.0
 1.0

In [49]:
v = readdlm("vectorB.csv", '|')


3×1 Array{Float64,2}:
 4.0
 5.0
 6.0

In [50]:
sumaRn(u,v)

¡Error! Distintas dimensiones!