<div class="alert alert-success" role="alert">
<h1>Programación en Julia: Notebook 10 </h1>
<h2>Facultad de Ciencias, UNAM </h2>
<h3>Joshua Briones Andrade || Compufísica </h3>
</div>

**a)** Escribe  un programa que realice el producto de una matriz en $ℝ^{nxm}$, por un vector en $ℝ^n$ las entradas tanto del vector como de la matriz deben leerse de un archivo.  

(Para facilitarte las cosas puedes convertir tu programa de producto punto “del ejercicio 8” en una función)

Sean la matriz A, tal que $A \in m_{nxm}$ y el vector B, tal que $B \in m_{n}$ tales que el producto punto es denotado como...

$$B_{n} \cdot A_{nxm}=
\begin{pmatrix}
b_1, &
b_2, &
\dots &
b_n\\\end{pmatrix}
\cdot
\begin{pmatrix}
a_{11} & a_{12} & \dots & a_{1m}\\
a_{21} & a_{22} & \dots & a_{2m}\\
\vdots & \vdots & \ddots& \vdots\\
a_{n1} & a_{n2} & \dots & a_{nm}\\\end{pmatrix}
=...$$


$$...=\begin{pmatrix}\sum_{i=1}^{n}{a_{i1}b{i}},
\sum_{i=1}^{n}{a_{i2}b{i}},
\dots ,
\sum_{i=1}^{n}{a_{im}b{i}}\\\end{pmatrix}$$

Crearemos el vector b que tiene las dimensiones (1x5) y después vamos a crear nuestra matriz A de (5x3)

In [2]:
b=randcycle(5)
b'

1×5 RowVector{Int64,Array{Int64,1}}:
 2  4  1  5  3

In [12]:
A1=hcat(randcycle(5),randcycle(5),randcycle(5))

5×3 Array{Int64,2}:
 5  3  3
 4  4  1
 1  5  5
 3  1  2
 2  2  4

Primero definimos la función sumM para poder sumar los términos y arrojar el resultado de cada componente.

-La n significa la dimension que comparten el vector b y la matriz A

-La m significa otra dimension de la matriz A

-b es el vector

-A es la matriz

In [3]:
function MultiMv(b,A)
    
    if size(A)[1] == length(b)
        s=0
        C=zeros(1,size(A)[2])
        for m ∈ 1:size(A)[2]
            for i ∈ 1:size(A)[1]
                s = s+A[i,m]*b[i]
            end
            C[1,m]=s
            s=0
        end
        C
    else
        println("La matriz y el vector no comparten dimensiones compa, arre")
    end
end

MultiMv (generic function with 1 method)

Corroboramos que si sirve nuestra formula comparandola con la multiplicacion por 'default' de Julia

In [13]:
MultiMv(b',A1)

1×3 Array{Float64,2}:
 48.0  38.0  37.0

In [14]:
b'*A1

1×3 RowVector{Int64,Array{Int64,1}}:
 48  38  37



**b)** Escribe  un programa que realice el producto de dos matrices en $ℝ^{nxm}$, el usuario debe insertar las entradas de las matrices.

Apóyate en tu programa anterior, pues es una generalización de este.

NOTA: En general, por convención cuando se multiplica una matriz por un vector se pone la matriz del lado izquierdo y el vector del lado derecho; y este a su vez se considera un vector columna. 



La formula para el producto interno de dos vectores es:

$$A_{nxm}\cdot B_{mxn}=\sum_{j=1}^{m} \sum_{i=1}^{n}{\alpha_{ij}\beta_{ij}}$$

$$A_{nxm} \cdot B_{mxn'}=
\begin{pmatrix}
a_{11} & a_{12} & \dots & a_{1m}\\
a_{21} & a_{22} & \dots & a_{2m}\\
\vdots & \vdots & \ddots& \vdots\\
a_{n1} & a_{n2} & \dots & a_{nm}\\\end{pmatrix}
\cdot
\begin{pmatrix}
b_{11} & b_{12} & \dots & b_{1n'}\\
b_{21} & b_{22} & \dots & b_{2n'}\\
\vdots & \vdots & \ddots& \vdots\\
b_{m1} & b_{m2} & \dots & b_{mn'}\\\end{pmatrix}=...$$

$$...=\begin{pmatrix}
\sum_{i=1}^{m}{a_{i1}b_{i1}} & \sum_{i=1}^{m}{a_{i2}b_{i1}} & \dots & \sum_{i=1}^{m}{a_{in'}b_{i1}} \\
\sum_{i=1}^{m}{a_{i1}b_{i2}} & \sum_{i=1}^{m}{a_{i2}b_{i2}} & \dots & \sum_{i=1}^{m}{a_{in'}b_{i2}} \\
\vdots & \vdots & \ddots& \vdots \\
\sum_{i=1}^{m}{a_{i1}b_{in}} & \sum_{i=1}^{m}{a_{i2}b_{in}} & \dots & \sum_{i=1}^{m}{a_{in'}b_{in}} \\
\\\end{pmatrix}$$

Crearemos la matriz A que tiene las dimensiones (2x4) y después vamos a crear nuestra matriz B de (4x3), asi que el producto de A y B sera una matriz de dimensiones (2x3)

In [149]:
Z = hcat(randcycle(4)-1,randcycle(4)-1)
A=Z'

2×4 Array{Int64,2}:
 3  0  1  2
 1  2  3  0

In [148]:
B=hcat(randcycle(4),randcycle(4),randcycle(4))

4×3 Array{Int64,2}:
 3  4  4
 1  1  1
 4  2  2
 2  3  3

In [152]:
#Para la funcion necesitamos comprobar que comparten las dimensiones correspondientes, por ello el primer "if"
#Utilizamos d' para poder trabajar con un renglon 'i' de la matriz A y luego solo aplicar la multiplicacion de Mat x Vec

function MultiMM(A,B)
    
    if size(A)[2] == size(B)[1]
    
        C=zeros(size(A)[1],size(B)[2])
        
        for i ∈ 1:size(A)[1]
            d=hcat(A[i,1:end])
            renglonA=d'
            s=0
            
            for m ∈ 1:size(B)[2]    
                for j ∈ 1:size(B)[1]
                    s = s+B[j,m]*d'[j]
                end
            C[i,m]=s
            s=0
            end
        end
        C
    else
        println("Las matrices no comparten dimensiones compa, arre")
    end
end

MultiMM (generic function with 1 method)

Corroboramos que si sirve nuestra formula comparandola con la multiplicacion por 'default' de Julia

In [144]:
MultiMM(A,B)

2×3 Array{Float64,2}:
 13.0  20.0  12.0
 20.0  13.0  17.0

In [145]:
A*B

2×3 Array{Int64,2}:
 13  20  12
 20  13  17