<div class="alert alert-danger" role="alert">
<h1>Ejercicios de programación en julia</h1>
<h2>COMPUTACIÓN</h2>
<h2>FÍSICA,FACULTAD DE CIENCIAS, UNAM </h2>
<h3>JOAQUIN MIRANDA SANTIAGO</h3>
</div>

# Ejercicio 10
### a) escribe un programas que realice el producto de una matriz en Rnxm por un vector en R^n

In [8]:
#definimos primero una función que calcule el producto interior
function multiplicación(u,v)
    if length(u)==length(v)
        s= 0
        for i in eachindex(u)
            s=s+(u[i]*v[i])
            end 
      s
    end
end


multiplicación (generic function with 1 method)

In [9]:

function Mxvec(A,a)
    if size(A)[2] == length(a)
        vector = zeros(size(A)[1])
        for i in 1:size(A)[1]
            vector[i] = multiplicación(A[i,:],a)
        end
        vector
    end
end 

Mxvec (generic function with 1 method)

In [10]:
#ejemplo
a=[1,2,3]
A=[1 2 3;4 5 6;4 5 6]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 4  5  6

In [11]:
Mxvec(A,a)

3-element Array{Float64,1}:
 14.0
 32.0
 32.0

## b) Escribe un programa que realice el producto de dos matrices en Rnxm.


In [12]:
function matxmat(A,B)

    if size(A)[2] == size(A)[1]

        matriz_R = zeros(size(A)[1]B[2])

        for renglon in 1:size(A)[1]
        for columna in 1:size(B)[2]

            matriz_R[renglon,columna] = multiplicación(A[renglon,:],B[:,columna])

        end
        end
        

       println(matriz_R)

    end

end   

matxmat (generic function with 1 method)

In [15]:
#ejemplo
B=[1 3 5; 3 6 7;1 2 7]

3×3 Array{Int64,2}:
 1  3  5
 3  6  7
 1  2  7

In [ ]:
matxmat(A,B)