<div class="alert alert-danger" role="alert">
<h1>Ejercicios de programación en julia</h1>
<h2>COMPUTACIÓN</h2>
<h2>FÍSICA,FACULTAD DE CIENCIAS, UNAM </h2>
<h3>JOAQUIN MIRANDA SANTIAGO</h3>
</div>

# Ejercicio 7
## a) Escribe un programa que sume vectores en $R^3$
#### los vectores se suman entrada por entrada.
#### si
$$
\hat{\alpha} =(\alpha_1,\alpha_2,\alpha_3)
$$
$$
\hat{\beta} =(\beta_1,\beta_2,\beta_3)
$$
#### entoces 
$$
\hat{\alpha}+\hat{\beta} =(\alpha_1+\beta_1,\alpha_2+\beta_2,\alpha_3+\beta_3)
$$


In [7]:
function suma_de_vectores(a,b)
     ϕ=zeros(a)
    if length(a) ==3
        if length(a)==length(b)
            for i in 1:3
                ϕ[i]= a[i]+b[i]
            end
            
            println("el vector resultente es:")
    println("ϕ=",ϕ)
            else 
            println("error!, los vectores deben de ser del mismo tamaño")
        end
        else 
        println("lo sentimos, el programa solo puede suamar vectores en R3 ")
    end
   
end

suma_de_vectores (generic function with 1 method)

### ejemplos

In [8]:
a=[1,2,3]
b=[3,2,1]

3-element Array{Int64,1}:
 3
 2
 1

In [10]:
suma_de_vectores(a,b)

el vector resultente es:
ϕ=[4, 4, 4]


In [11]:
c=[4,6,7]
d=[1,2]

2-element Array{Int64,1}:
 1
 2

In [12]:
suma_de_vectores(c,d)

error!, los vectores deben de ser del mismo tamaño


## b) Escribe un programa que sume dos vectores en $R^n$ las estradas de los vectores deben leerse de un archivo.

$$
\hat{\alpha} =(\alpha_1,\alpha_2,\alpha_3,...,\alpha_n)
$$
$$
\hat{\beta} =(\beta_1,\beta_2,\beta_3,...,\beta_n)
$$
#### las suma de $ \hat{\alpha} $ y $\hat{\beta}$ esta definida como:
$$
\hat{\alpha}+\hat{\beta} =(\alpha_1+\beta_1,\alpha_2+\beta_2,\alpha_3+\beta_3,...,\alpha_n+\beta_n)
$$

In [2]:
function suma_de_vectores(A,B)
     C=zeros(A)
        if length(A)==length(A)
            for i in 1:length(A)
                C[i]= A[i]+B[i]
            end
            
            println("el vector resultente es:")
    println("C=",C)
        else 
            println("error!, los vectores deben de ser del mismo tamaño")
        end
   
end

suma_de_vectores (generic function with 1 method)

In [1]:
#ejemplo
A=[1,2,3,4,5]
B=[5,4,3,2,1]

5-element Array{Int64,1}:
 5
 4
 3
 2
 1

In [3]:
suma_de_vectores(A,B)

el vector resultente es:
C=[6, 6, 6, 6, 6]
