In [28]:
function MatVec(mat,vec)
    if size(mat)[2] == length(vec) #Necesitamos que el tamaño del renglon dea igual al del vector
        R = zeros(size(mat)[1]) #Este sera el resultado con el tamaño de las columbas de A
        for i in 1:size(mat)[1] #Las operaciones e haran en las columnas de A
            l=0 #Esta variable guardara los elementos del renglon
            for j in 1:size(mat)[2] #las operaciones del segundo renglon de A
                m=mat[i,j]*vec[j] #Se multiplicara el ij(esimo) renglon de A por la del vector
                l+=m #Y le sumamos a k m para que  valla guardando
            end
            R[i]=l #este es nuestro vector resultante
        end
        print(R) #Pedimos que imprima r
    end
end

MatVec (generic function with 1 method)

In [16]:
M=[1 7 8;8 4 6;1 5 6]

3×3 Array{Int64,2}:
 1  7  8
 8  4  6
 1  5  6

In [17]:
V=[1,7,5]

3-element Array{Int64,1}:
 1
 7
 5

In [29]:
MatVec(M,V)

[90.0, 66.0, 66.0]

In [56]:
function MulMatr(A,B)
    if size(A)[2]== size(B)[1] #El numero de columnas de A tiene que ser igual que de renglones de B
        M= zeros(size(A)[1],size(B)[2]) #Creamos una matriz del tamaño de los renglones de A y las columnas de B
        for i in 1:size(A)[1] #A cada numero de los renglones de A
            l=1 #estas son las columnas de B
            while l<=size(A)[1] #si l es menor o igual al tamaño de los renglones de A entonces x=0
                x=0 #este es un contador y guarda el resultado de w
                for j in 1:size(B)[1] #A cada numero de los renglones de B
                    w=A[i,j]*B[j,l] #Y vamos multiplicando el i esimo con el j esimo 
                    x+=w #Se van sumando los resultados de w
                end
                Res[i,l]=x #Entonces x es cada iesimo del resultado
                l+=1 #Y vamos aumentando uno para que valla recorriendo en la matriz
            end
        end
        print(Res) #Imprimimos la matriz resultante
    end
end

MulMatr (generic function with 1 method)

In [58]:
A= [1 8 9; 5 4 5; 5 2 7]

3×3 Array{Int64,2}:
 1  8  9
 5  4  5
 5  2  7

In [54]:
MulMatr(A,B)

[115.0 103.0 34.0; 79.0 87.0 54.0; 81.0 97.0 56.0]

In [53]:
B=[4 7 8; 6 3 1;  7 8 2]

3×3 Array{Int64,2}:
 4  7  8
 6  3  1
 7  8  2