In [28]:
function MatVec(mat,vec)
    if size(mat)[2] == length(vec) # comparamos el tamaño de los vectores 
        R = zeros(size(mat)[1]) # hacemos el contador para el resultado 
        for i in 1:size(mat)[1] # operamos la columna de a 
            l=0 # guarda los reglones 
            for j in 1:size(mat)[2] # operaciones de la 2 columna de a 
                m=mat[i,j]*vec[j] # se multiplicara el ij
                l+=m # le sumamos para que llene el contador 
            end
            R[i]=l # el contador con el resultado 
        end
        print(R) # imprimimos el resutado 
    end
end

MatVec (generic function with 1 method)

In [16]:
M=[1 7 8;8 4 6;1 5 6]

3×3 Array{Int64,2}:
 1  7  8
 8  4  6
 1  5  6

In [17]:
V=[1,7,5]

3-element Array{Int64,1}:
 1
 7
 5

In [29]:
MatVec(M,V)

[90.0, 66.0, 66.0]

In [56]:
function MulMatr(A,B)
    if size(A)[2]== size(B)[1] # comparamos el tamaño de las matrices 
        M= zeros(size(A)[1],size(B)[2]) # creamos un contador para almacenar el mismo resultado 
        for i in 1:size(A)[1] # iniciamos el for 
            l=1 # marcamos las columnas de b 
            while l<=size(A)[1] # hacemos las condiciones del while
                x=0 # abrimos un contador que almacena el resultado de w 
                for j in 1:size(B)[1] # para los renglones de b 
                    w=A[i,j]*B[j,l] # multiplicamos i con cada j 
                    x+=w # se suman los resultados de w
                end
                Res[i,l]=x # x es cada ij 
                l+=1 # recorremos la matriz de 1 en 1 
            end
        end
        print(Res) # imprimimos el resultado 
    end
end

MulMatr (generic function with 1 method)

In [58]:
A= [1 8 9; 5 4 5; 5 2 7]

3×3 Array{Int64,2}:
 1  8  9
 5  4  5
 5  2  7

In [54]:
MulMatr(A,B)

[115.0 103.0 34.0; 79.0 87.0 54.0; 81.0 97.0 56.0]

In [53]:
B=[4 7 8; 6 3 1;  7 8 2]

3×3 Array{Int64,2}:
 4  7  8
 6  3  1
 7  8  2