<div class="alert alert-info" role="alert">
<p class ="lead"> 
<h1> Multiplicación de Vectores </h1>
<h3>Computación</h3> <h3>Física, Facultad de Ciencias. UNAM </h3>
<h2>Ethan Campos Méndez</h2> </div>

In [1]:
x=collect(0:1.0:16)

17-element Array{Float64,1}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
 11.0
 12.0
 13.0
 14.0
 15.0
 16.0

In [16]:
y=collect(16:1.0:32)

17-element Array{Float64,1}:
 16.0
 17.0
 18.0
 19.0
 20.0
 21.0
 22.0
 23.0
 24.0
 25.0
 26.0
 27.0
 28.0
 29.0
 30.0
 31.0
 32.0

In [15]:
z=collect(0:1.0:16)

17-element Array{Float64,1}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
 11.0
 12.0
 13.0
 14.0
 15.0
 16.0

In [17]:
for i ∈ eachindex(z)
    X=x[i]*y
    Y=y[i]*x
end

In [9]:
X=zeros()

0-dimensional Array{Float64,0}:
0.0

In [10]:
Y=zeros()

0-dimensional Array{Float64,0}:
0.0

In [18]:
X

17-element Array{Float64,1}:
 256.0
 272.0
 288.0
 304.0
 320.0
 336.0
 352.0
 368.0
 384.0
 400.0
 416.0
 432.0
 448.0
 464.0
 480.0
 496.0
 512.0

In [19]:
Y

17-element Array{Float64,1}:
   0.0
  32.0
  64.0
  96.0
 128.0
 160.0
 192.0
 224.0
 256.0
 288.0
 320.0
 352.0
 384.0
 416.0
 448.0
 480.0
 512.0