In [31]:
function SMatriz(A,B) 
    if size(A)==size(B)==(2,2) 
        R=zeros(size(A)) #Este sera el resultado que sera del mismo tamaño que A
        for i in 1:size(A)[1] #por cadaelemento del renglon 1 de A
            for j in 1:size(A)[2] #por cadaelemento del renglon 2 de A
                c=A[i,j]+B[i,j] #Y aqui sera por cada i y j esimo elemento de A en B
                R[i,j]=c #Se colocan los resultados en cada renglon y columna 
            end
        end
        print(R) #Aquí le pedimos que imprima R en la pantalla
    end
end

SMatriz (generic function with 1 method)

In [32]:
A=[1 4;6 8;]

2×2 Array{Int64,2}:
 1  4
 6  8

In [33]:
b=[4 5;-1 0;]

2×2 Array{Int64,2}:
  4  5
 -1  0

In [34]:
SMatriz(A,b)

[5.0 9.0; 5.0 8.0]

In [40]:
function SMatrizn(A,B) 
    if size(A)==size(B) 
        R=zeros(size(A)) #Este sera el resultado que sera del mismo tamaño que A
        for i in 1:size(A)[1] #por cadaelemento del renglon 1 de A
            for j in 1:size(A)[2] #por cadaelemento del renglon 2 de A
                c=A[i,j]+B[i,j] #Y aqui sera por cada i y j esimo elemento de A en B
                R[i,j]=c #Se colocan los resultados en cada renglon y columna
            end
        end
        print() #Aquí le pedimos que imprima R en la pantalla
    end
end

SMatrizn (generic function with 1 method)

In [41]:
g=[8 4 23 1;4 8 1 1;7 1 6 5]

3×4 Array{Int64,2}:
 8  4  23  1
 4  8   1  1
 7  1   6  5

In [42]:
h=[8 7 4  1;8  4 25 6;7 5 9 3]

3×4 Array{Int64,2}:
 8  7   4  1
 8  4  25  6
 7  5   9  3

In [43]:
SMatrizn(g,h)

[16.0 11.0 27.0 2.0; 12.0 12.0 26.0 7.0; 14.0 6.0 15.0 8.0]

In [44]:
l=[16.0 11.0 27.0 2.0; 12.0 12.0 26.0 7.0; 14.0 6.0 15.0 8.0]

3×4 Array{Float64,2}:
 16.0  11.0  27.0  2.0
 12.0  12.0  26.0  7.0
 14.0   6.0  15.0  8.0