In [15]:
function matriz(mat,vec)
    if size(mat)[2] == length(vec) 
        R = zeros(size(mat)[1]) 
        for i in 1:size(mat)[1] A
            l=0 
            for j in 1:size(mat)[2] 
                m=mat[i,j]*vec[j] 
                l+=m 
            end
            R[i]=l 
        end
        print(R) 
        
    end
end

matriz (generic function with 1 method)

In [16]:
M=[1 2 3;4 5 6;7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [17]:
V=[5,4,3]

3-element Array{Int64,1}:
 5
 4
 3

In [18]:
matriz(M, V)

LoadError: UndefVarError: A not defined

In [23]:
function Matriz(A,B)
    if size(A)[2]== size(B)[1] 
        M= zeros(size(A)[1],size(B)[2]) 
        for i in 1:size(A)[1] 
            l=1 
            while l<=size(A)[1] 
                x=0 
                for j in 1:size(B)[1] 
                    w=A[i,j]*B[j,l]  
                    x+=w 
                end
                Res[i,l]=x 
                l+=1 
            end
        end
        print(Res) 
    end
end

Matriz (generic function with 1 method)

In [24]:
A= [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [25]:
B=[4 7 8; 6 3 1;  7 8 2]

3×3 Array{Int64,2}:
 4  7  8
 6  3  1
 7  8  2

In [26]:
Matriz(A,B)

LoadError: UndefVarError: Res not defined