In [1]:
function Matriz(A,B) 
    if size(A)==size(B)==(2,2) 
        R=zeros(size(A)) 
        for i in 1:size(A)[1] 
            for j in 1:size(A)[2] 
                c=A[i,j]+B[i,j] 
                R[i,j]=c 
            end
        end
        print(R) 
    end
end

Matriz (generic function with 1 method)

In [2]:
A=[1 2;6 4;]


2×2 Array{Int64,2}:
 1  2
 6  4

In [3]:
b=[2 3;-1 0;]

2×2 Array{Int64,2}:
  2  3
 -1  0

In [4]:
Matriz(A,b)

[3.0 5.0; 5.0 4.0]

In [5]:
function Matriz2(A,B) 
    if size(A)==size(B) 
        R=zeros(size(A)) 
        for i in 1:size(A)[1] 
            for j in 1:size(A)[2] 
                c=A[i,j]+B[i,j] 
                R[i,j]=c 
            end
        end
        print() 
    end
end

Matriz2 (generic function with 1 method)

In [6]:
g=[3 2 12 14;7 9 56 7;4 1 3 8]

3×4 Array{Int64,2}:
 3  2  12  14
 7  9  56   7
 4  1   3   8

In [7]:
h=[5 5 5  5;5  4 25 9;3 3 3 3]


3×4 Array{Int64,2}:
 5  5   5  5
 5  4  25  9
 3  3   3  3

In [13]:
Matriz2(g,h)

In [12]:
l=[11.0 11.0 11.0 11.0; 24.0 2.0 32.0 8.0; 10.0 17.0 15.0 3.0]


3×4 Array{Float64,2}:
 11.0  11.0  11.0  11.0
 24.0   2.0  32.0   8.0
 10.0  17.0  15.0   3.0