a) Escribe un programa que realice el producto de una matriz en $$ R^{nxm}$$ por un vector en $$ R^n$$ Las entradas tanto del vector como de la matriz debenleerse de un archivo . (Para facilitarte las cosas puedes convertir tu
programa de producto punto “del ejercicio 8” en una función)

Generamos la función:

In [20]:
function MatxVec(m,v)
    if size(m)[2] == length(v) #Necesitamos que la dimensión de la matriz en las columnas sea igual a la del vector. Para que la operación sea válida
        C = zeros(size(m)[1]) #Se construye un arreglo con las dimensiones de los renglones de la matriz, y la del vector
        for i in 1:size(m)[1] #Las operaciones se realizan en losrenglones de C (los renglones se indican con el [1])
            l=0 #Esta variable guardara los elementos de las operaciones a continuación, para usarse posteriormente 
            for j in 1:size(m)[2] #Para cada j ésimo elemento que pertenece a la columnas de M se opera
                M=m[i,j]*v[j] #M toma el valo de el producto del i,j-ésimo de la matriz pon el j-ésimo renglón del vector
                l+=M #A l, reasignamos un nuevo valo que la adicción del último valo de l con el de la operación M
                end #Termina el ciclo for
            C[i]=l #este es nuestro vector resultante, a cada i ésimo elemento le correponde el final de l 
            end #Termina ciclo for
        print(C) #Pedimos que imprima el vector resultante que es C
        end #Termina ciclo condicional
end #Trmina la función 

MatxVec (generic function with 1 method)

In [21]:
M=[1 7 8;8 4 6;1 5 6]

3×3 Array{Int64,2}:
 1  7  8
 8  4  6
 1  5  6

In [22]:
v=[1,7,5]

3-element Array{Int64,1}:
 1
 7
 5

In [23]:
MatxVec(M,v)

[90.0, 66.0, 66.0]

b) Escribe un programa que realice el producto de dos matrices en $$R^{nxm} $$
, el
usuario debe insertar las entradas de las matrices. Apóyate en tu programa
anterior, pues es una generalización de este

In [1]:
function MM(A,B)
    if size(A)[2]== size(B)[1] #Abrimos el condicional. Es necesario que el tamaño de columna de A tiene que ser igual que de renglón de B
        M= zeros(size(A)[1],size(B)[2]) #Generamos una matriz nxm; n=tamaño de renglones de A y m=columnas de B
        for i in 1:size(A)[1] #A cada elemento de los renglones de A se hará lo siguiente:
            l=1 #estas son las columnas de B donde se asignan lo valores de las operaciones
            while l<=size(A)[1] #Mientras l sea menor o igual al tamaño de los renglones de A entonces,
                x=0 #x=0, este es un contador y guarda el resultado de w
                for j in 1:size(B)[1] #A cada elemento que pertenece a los renglones de B
                    w=A[i,j]*B[j,l] #Y w tom el valor del producto del i ésimo por el j ésimo elemento
                    x+=w #El contador toma el valor original adicionando el nuevo de w 
                end #Termina el ciclo for 
                R[i,l]=x #la variable x corresponde a cada i-l ésimo
                l+=1 #Y vamos recorriendo en la matriz un renglón
            end #Termina ciclo while
        end #Termina ciclo for
    print(R) #Imprimimos la matriz resultante
    end #Termina el condicional 
end #

MM (generic function with 1 method)

In [2]:
A= [1 8 9; 5 4 5; 5 2 7]

3×3 Array{Int64,2}:
 1  8  9
 5  4  5
 5  2  7

In [3]:
B=[4 7 8; 6 3 1;  7 8 2]

3×3 Array{Int64,2}:
 4  7  8
 6  3  1
 7  8  2

In [4]:
MM(A,B)

LoadError: UndefVarError: R not defined