a) Este programa entrega un archivo con los datos de un movimiento rectilíneo uniforme donde el usuario define la posición inicial, la velocidad inicial, los límites del intervalo de tiempo y el tamaño del intervalo. A continuación se muestra el modelo para este movimiento:

$$
\textbf{s} = s_0 + v_{0}t
$$

In [2]:
function mru(s0,v0,t0,tf,Δt)
    t = collect(t0:Δt:tf)
    s = zeros(t)
    for i in eachindex(t)
    s[i] = v0*t[i] + s0
    end
    variables = hcat(t,s)
    writedlm("mru.csv", variables, '|')
    datos = readdlm("mru.csv", '|')
    return(datos) #Leemos los datos y los mostramos como salida para comprobar que se creó el archivo
end

mru (generic function with 1 method)

In [3]:
mru(0,1,0,1,0.01)

101×2 Array{Float64,2}:
 0.0   0.0 
 0.01  0.01
 0.02  0.02
 0.03  0.03
 0.04  0.04
 0.05  0.05
 0.06  0.06
 0.07  0.07
 0.08  0.08
 0.09  0.09
 0.1   0.1 
 0.11  0.11
 0.12  0.12
 ⋮         
 0.89  0.89
 0.9   0.9 
 0.91  0.91
 0.92  0.92
 0.93  0.93
 0.94  0.94
 0.95  0.95
 0.96  0.96
 0.97  0.97
 0.98  0.98
 0.99  0.99
 1.0   1.0 

b) Este programa escribe en un archivo los datos de un movimiento uniformemente acelerado donde el usuario define la posición inicial, la velocidad inicial, la aceleración, el tiempo inicial, el tiempo final y el tamaño del intervalo de tiempo. En el modelo siguiente se muestra la relación de esas variables:

$$
\textbf{s} = s_0 + v_{0}t + \frac{1}{2}at^2
$$

In [4]:
function mua(s0,v0,a,t0,tf,Δt)
    t = collect(t0:Δt:tf)
    s = zeros(t)
    for i in eachindex(t)
    s[i] = v0*t[i] + s0 + 0.5*a*t[i]^2 #Solo se sustituyen el valor de las variables en cada tiempo para generar los datos del movimiento
    end
    variables = hcat(t,s)
    writedlm("mua.csv", variables, '|')
    datos = readdlm("mua.csv", '|')
    return(datos)
end

mua (generic function with 1 method)

In [5]:
mua(0,50,-9.81,0,11,0.125)

89×2 Array{Float64,2}:
  0.0      0.0    
  0.125    6.17336
  0.25    12.1934 
  0.375   18.0602 
  0.5     23.7737 
  0.625   29.334  
  0.75    34.7409 
  0.875   39.9946 
  1.0     45.095  
  1.125   50.0421 
  1.25    54.8359 
  1.375   59.4765 
  1.5     63.9637 
  ⋮               
  9.625   26.8477 
  9.75    21.2184 
  9.875   15.4359 
 10.0      9.5    
 10.125    3.41086
 10.25    -2.83156
 10.375   -9.22727
 10.5    -15.7763 
 10.625  -22.4785 
 10.75   -29.3341 
 10.875  -36.3429 
 11.0    -43.505  

c) Este programa entrega en un archivo los datos de un tiro parabólico dado que el usuario entregue los valores para la posición inicial, la altura inicial, la velocidad inicial, la aceleración, el tiempo inicial, el tiempo final y el tamaño del intervalo de tiempo. Este es un movimiento compuesto en dos ejes espaciales como se muestra en el modelo:

$$
\textbf{s} = (x_0 + v_{0x}t)\hat{i} + \left(-\frac{1}{2}gt^2+v_{0y}t+y_0\right)\hat{j}
$$

$$
\textbf{v} = v_0 cos(\theta)\hat{i} + (v_0 sen(\theta) -gt)\hat{j}
$$

In [6]:
function tp(x0,y0,v0,θ,t0,tf,Δt)
    t = collect(t0:Δt:tf)
    x = zeros(t)
    y = zeros(t)
    for i in eachindex(t)
    x[i] = x0 + v0*cos(θ)*t[i] #Con la velocidad inicial y el ángulo de tiro se determina la velocidad inicial en cada eje
    y[i] = y0 + v0*sin(θ)*t[i] - 0.5*9.81*t[i]^2
    end
    variables = hcat(t,x,y)
    writedlm("tp.csv", variables, '|')
    datos = readdlm("tp.csv", '|')
    return(datos)
end

tp (generic function with 1 method)

In [7]:
tp(0,0,100,π/4,0,15,0.125) #Se muestra un ejemplo con posición inicial cero y ángulo de 45°

121×3 Array{Float64,2}:
  0.0       0.0        0.0    
  0.125     8.83883    8.76219
  0.25     17.6777    17.3711 
  0.375    26.5165    25.8267 
  0.5      35.3553    34.1291 
  0.625    44.1942    42.2782 
  0.75     53.033     50.2739 
  0.875    61.8718    58.1165 
  1.0      70.7107    65.8057 
  1.125    79.5495    73.3416 
  1.25     88.3883    80.7243 
  1.375    97.2272    87.9537 
  1.5     106.066     95.0298 
  ⋮                           
 13.625   963.433     52.8657 
 13.75    972.272     44.9203 
 13.875   981.111     36.8215 
 14.0     989.949     28.5695 
 14.125   998.788     20.1642 
 14.25   1007.63      11.6056 
 14.375  1016.47       2.89373
 14.5    1025.3       -5.97142
 14.625  1034.14     -14.9898 
 14.75   1042.98     -24.1616 
 14.875  1051.82     -33.4866 
 15.0    1060.66     -42.9648 