<div class="alert alert-success" role="alert">
<h1>Programación en Julia: Notebook 7 </h1>
<h2>Facultad de Ciencias, UNAM </h2>
<h3>Joshua Briones Andrade || Compufísica </h3>
</div>

**a)** Escribe un programa que sume dos vectores en ℝ^3, se debe insertar las entradas de los vectores. 

Para este ejercicio vamos a utilizar la definición de la suma de vectores para ℝ^3 donde se suma componente con componente.  

$$ \vec A + \vec B = (a\hat x+a\hat y+a\hat z)+(b\hat x+b\hat y+b\hat z)= (a+b)\hat x + (a+b)\hat y + (a+b)\hat z=\vec C $$

In [9]:
function SumVec3(A,B)
    if length(A)==length(B)
        c=zeros(A)
        for i ∈ eachindex(A)
            c[i]=A[i]+B[i]
        end
        C=hcat(c[1],c[2],c[3])
        C
    else
        "No son de las mismas dimensiones compa, arre"
    end
end

SumVec3 (generic function with 1 method)

In [10]:
#Caso DIFERENTES DIMENSIONES

A=[1,2,3,4]; B=[1,1,1]
SumVec3(A,B)

"No son de las mismas dimensiones compa, arre"

In [11]:
#Caso MISMAS DIMENSIONES

A=(1,2,34); B=(1,1,1)
SumVec3(A,B)

1×3 Array{Float64,2}:
 2.0  3.0  35.0

**b)** Escribe  un programa que sume dos vectores en ℝ^n las entradas de los vectores deben leerse de un archivo de datos. (recuerda que esto solo tiene sentido si los vectores a sumar son de la misma dimensión)

$$ \vec A + \vec B = (a_1,a_2,a_3,...,a_n)+(b_1,b_2,b_3,...,b_n)= [(a+b)_1 ,(a+b)_2 ,(a+b)_3,..., (a+b)_n] = \vec C $$

In [68]:
function SumVec(A,B)
    if length(A)==length(B)
        c=zeros(A)
        for i ∈ eachindex(A)
            c[i]=A[i]+B[i]
        end
        C=c[1:length(A)]
        C'
    else
        "No son de las mismas dimensiones compa, arre"
    end
end

SumVec (generic function with 2 methods)

In [90]:
#Caso DIFERENTES DIMENSIONES

D=hcat(7,1,6,1); C=hcat(1,1,1)
SumVec(A,C)

"No son de las mismas dimensiones compa, arre"

In [91]:
#Caso MISMAS DIMENSIONES

A=hcat(1,2,4,1); B=hcat(1,1,1,0)
SumVec(A,B)

1×4 RowVector{Int64,Array{Int64,1}}:
 2  3  5  1

In [92]:
T=vcat(A,B,D)
writedlm("SumVec.csv",T,'|')
readdlm("SumVec.csv",'|')

3×4 Array{Float64,2}:
 1.0  2.0  4.0  1.0
 1.0  1.0  1.0  0.0
 7.0  1.0  6.0  1.0

In [93]:
function SumVec(AB)
    c=zeros(1,size(AB)[2])
    for i ∈ 1:size(AB)[2]
        s=0
        j=1
        for m ∈ 1:size(AB)[1]
        s=s+AB[j,i]
        j=j+1 
        end
    c[i]=s
    end
C=c[1:length(A)]
C'
end

SumVec (generic function with 2 methods)

In [94]:
readdlm("SumVec.csv",'|')

3×4 Array{Float64,2}:
 1.0  2.0  4.0  1.0
 1.0  1.0  1.0  0.0
 7.0  1.0  6.0  1.0

In [95]:
SumVec(readdlm("SumVec.csv",'|'))

1×4 RowVector{Float64,Array{Float64,1}}:
 9.0  4.0  11.0  2.0