<div class="alert alert-success" role="alert">
<h1>Programación en Julia: Notebook 8 </h1>
<h2>Facultad de Ciencias, UNAM </h2>
<h3>Joshua Briones Andrade || Compufísica </h3>
</div>

**a)** Calcular el producto interior (producto punto) de dos vectores en ℝ^3 el usuario debe insertar las entradas de los vectores. 

Recurrimos a la definición del producto interior para vectores en ℝ^3 y sabemos que...

$$ \vec A \cdot \vec B = (a_1,a_2,a_3)\cdot(b_1,b_2,b_3)=(a_1b_1,a_2b_2,a_3b_3)=\vec D $$

In [26]:
function Dot3(A,B)
    if length(A)==length(B)
        C=zeros(A)
        for i in eachindex(A)
            C[i]=A[i]*B[i]
        end
        C'
    else 
        println("No tienen las mismas dimensiones compa, arre")
    end
end

Dot3 (generic function with 1 method)

In [29]:
A=[11,5,2,1];B=[9,3,6]
Dot3(A,B)

No tienen las mismas dimensiones compa, arre


In [30]:
A=[11,5,2];B=[9,3,6]
Dot3(A,B)

1×3 RowVector{Int64,Array{Int64,1}}:
 99  15  12

**b)** Escribe  un programa que realice el producto interior (producto punto) de dos vectores en ℝ^n las entradas de los vectores deben leerse de un archivo. 

(Recuerda nuevamente que esto solo tiene sentido si los vectores son de la misma dimensión).

Recurrimos a la definición del producto interior para vectores en ℝ^n (generalizada) y la aplicamos a la funcion "Dot".

$$ \vec A \cdot \vec B = (a_1,a_2,a_3,...,a_n)\cdot(b_1,b_2,b_3,...,b_n)=(a_1b_1,a_2b_2,a_3b_3,...,a_nb_n)=\vec D $$

In [18]:
function Dot(A,B)
    if length(A)==length(B)
        C=zeros(A)
        for i in eachindex(A)
            C[i]=A[i]*B[i]
        end
        C
    else 
        println("No tienen las mismas dimensiones compa, arre")
    end
end

Dot (generic function with 1 method)

In [19]:
A=hcat(11,5,2,1);B=hcat(0,9,3,6)
Dot(A,B)

1×4 Array{Int64,2}:
 0  45  6  6

In [20]:
#Para que trabaje con componentes decimales se tiene que aclarar que cada componente es flotante.
A=[11.0,5.0,2.0,1.0,9,99.9,5,4,3];B=[0.0,9.0,3.0,6.02,3.11,.78907,2,3,4]

Dot(A,B)

9-element Array{Float64,1}:
  0.0   
 45.0   
  6.0   
  6.02  
 27.99  
 78.8281
 10.0   
 12.0   
 12.0   

In [22]:
function Dot(AB)
    C=zeros(1,size(AB)[2])
    for i ∈ 1:size(AB)[2]
        C[i]=A[i]*B[i]
    end
    C
end

Dot (generic function with 2 methods)

In [13]:
T=vcat(A,B)
writedlm("Dot.csv",T,'|')
readdlm("Dot.csv",'|')

2×4 Array{Float64,2}:
 11.0  5.0  2.0  1.0
  0.0  9.0  3.0  6.0

In [23]:
Dot(readdlm("Dot.csv",'|'))

1×4 Array{Float64,2}:
 0.0  45.0  6.0  6.02