<div class="alert alert-success" role="alert">
<h1>Programación en Julia: Notebook 9 </h1>
<h2>Facultad de Ciencias, UNAM </h2>
<h3>Joshua Briones Andrade || Compufísica </h3>
</div>

**a)** Sumar dos matrices en $ ℝ^{2x2} $, el usuario debe insertar las entradas de las 
matrices. 

Sean dos matrices $ A,B \in m_{2x2} $ tales que la suma de las matrices es...

$$ A_{2x2}+B_{2x2} = 
\begin{pmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\\end{pmatrix} 
+
\begin{pmatrix}
b_{11} & b_{12}\\
b_{21} & b_{22}\\\end{pmatrix}=... $$ 

$$
...=\begin{pmatrix}
a_{11}+b_{11} & a_{12}+b_{12}\\
    a_{21}+b_{21} & a_{22}+b_{22}\\\end{pmatrix}=C_{2x2} $$

Para empezar vamos a definir los renglones i, j y un ciclo for que contenga a otro dentro de este para que recorra todos los componentes de la matriz.

In [78]:
function SumMat2(A,B)
    n=size(A)
    
    if n !=size(B)
        println("No se puede compa, no tienen las mismas dimensiones, saludos")
    else
        C=zeros(A)
        i=1
        j=1
        for h ∈ 1:2
            for m ∈ 1:2
            C[i,j]=A[i,j]+B[i,j]
            i=i+1
            end
            i=1
            j=j+1
        end
        C
    end
end      

SumMat2 (generic function with 1 method)

In [80]:
#Primer matriz cuadrada "A"
A=hcat([1,2],[3,4])

2×2 Array{Int64,2}:
 1  3
 2  4

In [81]:
#Segunda matriz cuadrada "B"
B=hcat([2,2],[2,2])

2×2 Array{Int64,2}:
 2  2
 2  2

In [65]:
#Ultima matriz "C"
C=hcat([2,2],[2,2],[3,3])

2×3 Array{Int64,2}:
 2  2  3
 2  2  3

In [82]:
#Caso MISMAS DIMENSIONES

SumMat2(A,B)

2×2 Array{Int64,2}:
 3  5
 4  6

In [73]:
#Caso DIFERENTES DIMENSIONES

SumMat(A,C)

No se puede compa, no tienen las mismas dimensiones, saludos


**b)** Escribe  un programa que sume dos matrices en $ ℝ^{nxn} $, las entradas de las matrices deben leerse de un archivo. 

(Recuerda también que esto solo tiene sentido si las matrices a sumar son de la misma dimensión)

Sean dos matrices $ A,B \in m_{mxn} $ tales que la suma de las matrices es...

$$ A_{mxn}+B_{mxn} = 
\begin{pmatrix}
a_{11} & a_{12} & \dots & a_{1m}\\
a_{21} & a_{22} & \dots & a_{2m}\\
\vdots & \vdots & \ddots& \vdots\\
a_{n1} & a_{n2} & \dots & a_{nm}\\\end{pmatrix} 
+
\begin{pmatrix}
b_{11} & b_{12} & \dots & b_{1m}\\
b_{21} & b_{22} & \dots & b_{2m}\\
\vdots & \vdots & \ddots& \vdots\\
b_{n1} & a_{n2} & \dots & a_{nm}\\\end{pmatrix}=... $$ 

$$
...=\begin{pmatrix}
a_{11}+b_{11} & a_{12}+b_{12} & \dots & a_{1m}+b_{1m}\\
a_{21}+b_{21} & a_{22}+b_{22} & \dots & a_{2m}+b_{2m}\\
\vdots & \vdots & \ddots& \vdots\\
    a_{n1}+b_{n1} & a_{n2}+b_{n2} & \dots & a_{nm}+b_{nm}\\\end{pmatrix}=C_{mxn} $$

Para el caso generalizado definimos los renglones i, j y un ciclo for que considere las dimesiones de las matrices para repetirse i o j veces, este contendra a otro dentro ciclo for para que recorra todos los componentes de la matriz.


In [83]:
function SumMat(A,B)
    n=size(A)
    
    if n !=size(B)
        println("No se puede compa, no tienen las mismas dimensiones, saludos")
    else
        C=zeros(A)
        i=1
        j=1
        for h ∈ 1:n[2]
            for m ∈ 1:n[1]
            C[i,j]=A[i,j]+B[i,j]
            i=i+1
            end
            i=1
            j=j+1
        end
        C
    end
end      

SumMat (generic function with 1 method)

In [76]:
#Se define la primer matriz como un arreglo de vectores al que llamaremos A

A = hcat(randcycle(5)-1,randcycle(5)-1,randcycle(5)-1,randcycle(5)-1,randcycle(5)-1)

5×5 Array{Int64,2}:
 3  3  3  2  3
 2  4  4  3  0
 0  0  0  4  1
 4  1  1  0  4
 1  2  2  1  2

In [43]:
#Después definimos la segunda matriz como un arreglo de vectores que se llame B

B = hcat(randcycle(5)-1,randcycle(5)-1,randcycle(5)-1,randcycle(5)-1,randcycle(5)-1)

5×5 Array{Int64,2}:
 4  4  2  3  1
 2  3  3  2  3
 3  0  1  0  4
 0  2  4  4  2
 1  1  0  1  0

In [19]:
#Se define una tercera matriz como un arreglo de vectores de diferente tamaño a la matriz A y B

C = hcat(randcycle(5),randcycle(5),randcycle(5),randcycle(5),randcycle(5),randcycle(5))

5×6 Array{Int64,2}:
 4  4  4  5  4  4
 3  5  3  3  1  1
 5  1  5  1  2  5
 2  2  2  2  5  3
 1  3  1  4  3  2

In [46]:
#Caso MISMAS DIMENSIONES

SumMat(A,B)

5×5 Array{Int64,2}:
 5  6  4  4  2
 4  7  7  6  6
 7  1  2  3  8
 0  2  4  4  4
 4  4  3  3  0

In [77]:
#Caso DIFERENTES DIMENSIONES

SumMat(A,C)

No se puede compa, no tienen las mismas dimensiones, saludos
