# Ejercicio 1#


### a) ###

In [1]:
function(prom(a,b)) #definimos la función
    promedio = (a+b)/2 #las operaciones necesarias par el calculo
end


prom (generic function with 1 method)

In [2]:
#ejemplo
a=147
b=35
prom(a,b)

91.0

### b) ###

In [3]:
function(Sumahasta(N)) #definimos la función 
    n=0
    for i ∈ 0:N  
        n=n+i #como i se "mueve de uno en uno" la suma se actualiza con el valor siguente en el intervalo
    end
    println(n)
end

Sumahasta (generic function with 1 method)

In [4]:
#ejemplo
N=10
Sumahasta(100)

5050


### c) ###

In [5]:
function(factorialde(N)) #definimos la función 
    if N ≤ 1 # si  "N" es 0 o 1 el factorial corresponde a 1 
        1
    else
        N*factorialde(N-1) 
        #cuando es diferente la funcion se vuelve recursiva y regrasa hasta un numero que puede calcular yde ahi continua
    end
end

factorialde (generic function with 1 method)

In [6]:
#ejemplo de cuando es 0  o  1
factorialde(1)

1

In [7]:
#ejemplo de cuando no 
factorialde(10)

3628800

### d) ###

In [8]:
function(potencia(a,b)) #definimos la función
    n = a^b #como solo se realiza una operacion no se requiere de ningún ciclo
end

potencia (generic function with 1 method)

In [9]:
#ejemplo
potencia(350,5)

5252187500000

#  Ejercicio 2 #

In [10]:
function(combinatoria(n,r)) #definimos la función
    C = factorialde(n)/(factorialde(n-r)*factorialde(r)) #nos apoyamos de la funcion "factorialde(N)" y realizamos los calculo
    println(C)
end

combinatoria (generic function with 1 method)

In [11]:
#ejemplo
combinatoria(4,3)

4.0


# Ejercicio 3 #

In [12]:
function(aproxPi(N)) #definimos la función
    aprox=0
    for n ∈ 0:N
        aprox = aprox + (-1)^n/((2*n)+1) #la suma se actualiza con el valor del su¿iguiente sumando
    end
    aprPi = 4*aprox 
    println(aprPi)
end

aproxPi (generic function with 1 method)

In [13]:
#ejemplo
aproxPi(100)

3.1514934010709914


# Ejercicio 4 #

In [14]:
function(aproxe(N)) #definimos la función
aprx = 0
    for n ∈ 0.0:N
        aprx = aprx + 1/factorialde(n)
    float(factorialde(n))
    end
    println(aprx)
end

aproxe (generic function with 1 method)

In [15]:
#ejemplo
aproxe(1000)

2.7182818284590455


x2+4x+4

In [17]:
function chicharonera(a,b,c) #definimos la funcion
   if b^2-4*a*c > 0 #identifica si el discriminante es mayor a cero y evalua la formula general 
        print("raiz real")# imprime que se trata de una raiz real
         X₋ =(-b-sqrt(b^2-4*a*c))/2*a#evalua el caso de la raiz negativa 
         X⁺ =(-b+sqrt(b^2-4*a*c))/2*a#evalua el caso de la raiz positiva
    X = hcat(X⁺,X₋)
    print(X)#por ultimo imprime ambos resultados
    
    end
    if b^2-4*a*c < 0#identifica si el discriminante es menor a cero y evalua la formula general multiplicando por un numero complejo
        print("raiz compleja")# imprime que se trata de una raiz compleja
         X₋ =(-b-sqrt((1im)*b^2-4*a*c))/2*a#evalua el caso de la raiz negativa
         X⁺ =(-b+sqrt((1im)*b^2-4*a*c))/2*a#evalua el caso de la raiz positiva
    X = hcat(X⁺,X₋)
    print(X)#por ultimo imprime ambos resultados
    end
    if b^2-4*a*c == 0#identifica si el discriminante es igual a cero y evalua la formula general 
        print("raiz doble")# imprime que se trata de una raiz doble
         X₋ =(-b-sqrt(b^2-4*a*c))/2*a#evalua el caso de la raiz negativa
         X⁺ =(-b+sqrt(b^2-4*a*c))/2*a#evalua el caso de la raiz positiva
    X = hcat(X⁺,X₋)
    print(X)#por ultimo imprime ambos resultados
    
    end
   
end

chicharonera (generic function with 1 method)

In [19]:
#ejemplo de raiz real
chicharonera(3,5,2)

raiz real[-6.0 -9.0]

In [18]:
#ejemplo de raiz compleja
chicharonera(6,5,2)

raiz complejaComplex{Float64}[-9.75204+21.4369im -20.248-21.4369im]

In [20]:
#ejemplo de riz doble
chicharonera(1,2,1)

raiz doble[-1.0 -1.0]

# Ejercicio 6 #

In [1]:
function producvect(a,b) #definimos la funcion
    if length(a)==length(b) #verifica que las dimensiones delos vectores sean iguales para comenzar a opeerar
        vectresult=zeros(a) #el resultado tiene las mismas dimensiones
        entr1=(a[3]*b[2])-(a[2]*b[3]) #realiza las operaciones respectivas
        entr2=(a[3]*b[1])-(a[1]*b[3])
        entr3=(a[2]*b[1])-(a[1]*b[2])
           vectresult=hcat(entr1,entr2,entr3)#acomoda cada entrada del vector resultante
        else #si no son iguales 
        println("las dimensiones son distintas") #escribe "las dimensiones son distintas" 
    end 
end

producvect (generic function with 1 method)

In [2]:
#ejemplo
a = [1,2,3,9]
b = [3,6,9,]

3-element Array{Int64,1}:
 3
 6
 9

In [3]:
producvect(a,b)

las dimensiones son distintas


In [4]:
#ejemplo
a = [2,2,3]
b = [3,9,9]

3-element Array{Int64,1}:
 3
 9
 9

In [5]:
producvect(a,b)

1×3 Array{Int64,2}:
 9  -9  -12

# Ejercicio 7 #

### a) ###

In [12]:
a = [1,2,3,]
b = [3,6,9,]

3-element Array{Int64,1}:
 3
 6
 9

In [7]:
function vectrsuma(a,b) # definimos la funcion
   vectsuma =zeros(a) #el vector resultante debe tenerla misma dimension quelos vectores que se suman
    if length(a) == length(b) #identifica las dimensiones
    for i ∈ eachindex(a,b)
    vectsuma[i] =a[i]+b[i] #hece las operaciones
    end
    println(vectsuma)

        else #cuando las dimensiones son distintas imprime
        "error tamaño de los vectores distinto"
end
end


vectrsuma (generic function with 1 method)

### a) ###

In [19]:
#ejemplo
vectrsuma(a,b)

[4,8,12]


### b) ###

In [20]:
#ejemplo
a = [1,2,3,9]
b = [3,6,9,6]
vectrsuma(a,b)

[4,8,12,15]


# Ejercicio 8 #

In [21]:
function prodint(a,b)
    producint = 0
if length(a) == length(b)
    for i ∈ eachindex(a,b)
    producint =producint + a[i]*b[i] 
    end
    println(producint)

else
    "error tamaño de los vectores distinto"
end
end

prodint (generic function with 1 method)

### a) ###

In [26]:
#ejemplo
a = [1,2,3]
b = [3,6,9]
prodint(a,b)

42


### b) ###

In [27]:
a = [1,2,3,4]
b = [3,6,9,6]
prodint(a,b)

66


# Ejercicio 11 #

### a) ###

In [26]:
m =3
b = 0

0

In [32]:
function recta(m,b,X) #define la funcion
Y = zeros(X) #define el tamaño de la imagen
for i ∈ eachindex(X)
    Y[i] = m*X[i] + b #para cada valor de X escribe un valor para Y 
end
    print(Y) #imprime todos los resultados de Y
end


recta (generic function with 1 method)

In [34]:
#ejemplo
X = collect(0:0.125:500);
m =3
b = 0
recta(m,b,X)

[0.0,0.375,0.75,1.125,1.5,1.875,2.25,2.625,3.0,3.375,3.75,4.125,4.5,4.875,5.25,5.625,6.0,6.375,6.75,7.125,7.5,7.875,8.25,8.625,9.0,9.375,9.75,10.125,10.5,10.875,11.25,11.625,12.0,12.375,12.75,13.125,13.5,13.875,14.25,14.625,15.0,15.375,15.75,16.125,16.5,16.875,17.25,17.625,18.0,18.375,18.75,19.125,19.5,19.875,20.25,20.625,21.0,21.375,21.75,22.125,22.5,22.875,23.25,23.625,24.0,24.375,24.75,25.125,25.5,25.875,26.25,26.625,27.0,27.375,27.75,28.125,28.5,28.875,29.25,29.625,30.0,30.375,30.75,31.125,31.5,31.875,32.25,32.625,33.0,33.375,33.75,34.125,34.5,34.875,35.25,35.625,36.0,36.375,36.75,37.125,37.5,37.875,38.25,38.625,39.0,39.375,39.75,40.125,40.5,40.875,41.25,41.625,42.0,42.375,42.75,43.125,43.5,43.875,44.25,44.625,45.0,45.375,45.75,46.125,46.5,46.875,47.25,47.625,48.0,48.375,48.75,49.125,49.5,49.875,50.25,50.625,51.0,51.375,51.75,52.125,52.5,52.875,53.25,53.625,54.0,54.375,54.75,55.125,55.5,55.875,56.25,56.625,57.0,57.375,57.75,58.125,58.5,58.875,59.25,59.625,60.0,60.375,60.75,61.125,6

544.875,545.25,545.625,546.0,546.375,546.75,547.125,547.5,547.875,548.25,548.625,549.0,549.375,549.75,550.125,550.5,550.875,551.25,551.625,552.0,552.375,552.75,553.125,553.5,553.875,554.25,554.625,555.0,555.375,555.75,556.125,556.5,556.875,557.25,557.625,558.0,558.375,558.75,559.125,559.5,559.875,560.25,560.625,561.0,561.375,561.75,562.125,562.5,562.875,563.25,563.625,564.0,564.375,564.75,565.125,565.5,565.875,566.25,566.625,567.0,567.375,567.75,568.125,568.5,568.875,569.25,569.625,570.0,570.375,570.75,571.125,571.5,571.875,572.25,572.625,573.0,573.375,573.75,574.125,574.5,574.875,575.25,575.625,576.0,576.375,576.75,577.125,577.5,577.875,578.25,578.625,579.0,579.375,579.75,580.125,580.5,580.875,581.25,581.625,582.0,582.375,582.75,583.125,583.5,583.875,584.25,584.625,585.0,585.375,585.75,586.125,586.5,586.875,587.25,587.625,588.0,588.375,588.75,589.125,589.5,589.875,590.25,590.625,591.0,591.375,591.75,592.125,592.5,592.875,593.25,593.625,594.0,594.375,594.75,595.125,595.5,595.875,596.25

38,1386.75,1387.13,1387.5,1387.88,1388.25,1388.63,1389.0,1389.38,1389.75,1390.13,1390.5,1390.88,1391.25,1391.63,1392.0,1392.38,1392.75,1393.13,1393.5,1393.88,1394.25,1394.63,1395.0,1395.38,1395.75,1396.13,1396.5,1396.88,1397.25,1397.63,1398.0,1398.38,1398.75,1399.13,1399.5,1399.88,1400.25,1400.63,1401.0,1401.38,1401.75,1402.13,1402.5,1402.88,1403.25,1403.63,1404.0,1404.38,1404.75,1405.13,1405.5,1405.88,1406.25,1406.63,1407.0,1407.38,1407.75,1408.13,1408.5,1408.88,1409.25,1409.63,1410.0,1410.38,1410.75,1411.13,1411.5,1411.88,1412.25,1412.63,1413.0,1413.38,1413.75,1414.13,1414.5,1414.88,1415.25,1415.63,1416.0,1416.38,1416.75,1417.13,1417.5,1417.88,1418.25,1418.63,1419.0,1419.38,1419.75,1420.13,1420.5,1420.88,1421.25,1421.63,1422.0,1422.38,1422.75,1423.13,1423.5,1423.88,1424.25,1424.63,1425.0,1425.38,1425.75,1426.13,1426.5,1426.88,1427.25,1427.63,1428.0,1428.38,1428.75,1429.13,1429.5,1429.88,1430.25,1430.63,1431.0,1431.38,1431.75,1432.13,1432.5,1432.88,1433.25,1433.63,1434.0,1434.38,1434.

### b) ###

In [35]:
function(parabola(A,B,C)) #define la funcion
Y=zeros(X) #define el tamaño de Y
for i in eachindex(X)
    Y[i] = A*(X[i])^2+B*X[i]+C #utiliza la expresion "ax^2+bx+c" para llenar el arreglode Y
end
    Y
end

parabola (generic function with 1 method)

In [36]:
#ejemplo
parabola(10,30,6)

4001-element Array{Float64,1}:
  6.0      
  9.90625  
 14.125    
 18.6563   
 23.5      
 28.6563   
 34.125    
 39.9063   
 46.0      
 52.4063   
 59.125    
 66.1563   
 73.5      
  ⋮        
  2.50123e6
  2.50248e6
  2.50373e6
  2.50499e6
  2.50624e6
  2.50749e6
  2.50874e6
  2.50999e6
  2.51125e6
  2.5125e6 
  2.51375e6
  2.51501e6

# Ejercicio 12 #

### a) ###

In [47]:
function MRU(v,t) #definimos la funcion en terminos de la velocidad y el tiempo
posicion = zeros(length(t))#el tamaño debe ser el mismo que el del tiempo
for i ∈ 1:length(t)
    if i != 1 #para todas las posiciones excepto la primera se actualizarán atravez de laformula de la velocidad
        posicion[i] = posicion[i-1]+v*Δt
    end
end
    MRU=hcat(t,posicion) #se cea un arreglo de la posicion contra el tiempo
writedlm("datosMRU.txt",MRU,'|') #se escribe el archivo
readdlm("datosMRU.txt",'|') #lo lee
end
    

MRU (generic function with 1 method)

In [52]:
#ejemplo
Δt = 0.25
t = 0:Δt:30
MRU(58,t);

### b) ###

In [53]:
function caidalibre(t,y0) #definimos la funcion enterminos del tiempo y la posicion inicial
    g=9.81 #definimos las constantes
    Y=zeros(t)#el tamaño del arreglo para Y
    for i ∈ eachindex(t)#realiza la operaciones convenientes para el movimiento visto desde la perspectiva vertical (Y)
        Y[i]=y0-((g*t[i]^2)/2)
    end
 caidlibr=hcat(t,Y) #se cea un arreglo de la posicion en Y contra el tiempo
writedlm("datoscaidalibre.txt",caidlibr,'|') #se escribe el archivo
readdlm("datoscaidalibre.txt",'|') #lo lee
end    

caidalibre (generic function with 1 method)

In [55]:
#ejemplo
t = 0:.25:40
y0=200
caidalibre(t,y0)

161×2 Array{Float64,2}:
  0.0     200.0  
  0.25    199.693
  0.5     198.774
  0.75    197.241
  1.0     195.095
  1.25    192.336
  1.5     188.964
  1.75    184.978
  2.0     180.38 
  2.25    175.168
  2.5     169.344
  2.75    162.906
  3.0     155.855
  ⋮              
 37.25  -6605.99 
 37.5   -6697.66 
 37.75  -6789.93 
 38.0   -6882.82 
 38.25  -6976.32 
 38.5   -7070.44 
 38.75  -7165.16 
 39.0   -7260.51 
 39.25  -7356.46 
 39.5   -7453.03 
 39.75  -7550.21 
 40.0   -7648.0  

In [50]:
function Tiroparabolico(t,θ,v0)#definimos la funcion enterminos del tiempo el angulo y la velocidad inicial
g = 9.81                  #definimos las constantes
v = v0*cos(θ)+v0*sin(θ) #la velocidad como vector
X = zeros(t)#el tamaño del arreglo para X
Y = zeros(t)#el tamaño del arreglo para Y
for i ∈ eachindex(t) #realiza la operaciones convenientes para el movimiento visto desde la perspectiva horizontal (X) y la perspectiva vertical (Y)
    X[i]=v0*cos(θ)*t[i]
    Y[i]=(-1(0.5*g*t[i]^2)+v0*sin(θ)*t[i])
end
     tiro_parabol=hcat(t,X,Y) #se cea un arreglo de las posiciones en X y Y contra el tiempo
writedlm("datostir_parabol.txt",tiro_parabol,'|')#se escribe el archivo
readdlm("datostir_parabol.txt",'|')#lo lee
    
end

Tiroparabolico (generic function with 1 method)

In [51]:
#ejemplo
t = 0.0:0.25:100
θ=π/16
v0=36
Tiroparabolico(t,θ,v0)

401×3 Array{Float64,2}:
   0.0      0.0           0.0     
   0.25     8.82707       1.44925 
   0.5     17.6541        2.28538 
   0.75    26.4812        2.50838 
   1.0     35.3083        2.11825 
   1.25    44.1353        1.115   
   1.5     52.9624       -0.501373
   1.75    61.7895       -2.73087 
   2.0     70.6165       -5.5735  
   2.25    79.4436       -9.02925 
   2.5     88.2707      -13.0981  
   2.75    97.0977      -17.7801  
   3.0    105.925       -23.0752  
   ⋮                              
  97.25  3433.73     -45706.3     
  97.5   3442.56     -45943.4     
  97.75  3451.38     -46181.1     
  98.0   3460.21     -46419.3     
  98.25  3469.04     -46658.2     
  98.5   3477.86     -46897.7     
  98.75  3486.69     -47137.9     
  99.0   3495.52     -47378.6     
  99.25  3504.35     -47620.0     
  99.5   3513.17     -47861.9     
  99.75  3522.0      -48104.5     
 100.0   3530.83     -48347.7     