In [1]:
function matvec(m,v)
    if size(m)[2] == length(v)#Comparamos que el tamaño del vetcor sea igual al número de renglones de la matriz
        p= zeros(size(m)[1])#Hacemos un contador 
        for i in 1:size(m)[1]#Para cada elemento de los renglones de la matriz
            l=0 # Guarda los renglones 
            for j in 1:size(m)[2] #Para cada elemento de las columnas d la amtriz
                n=m[i,j]*v[j] #Se multiplicará el renglón por columna
                l+=n#a l le sumamos el valor de l
            end
            p[i]=l #El contador es igual a el resultado
        end
        print(p) #Imprimimos el resultado 
    end
end

matvec (generic function with 1 method)

In [2]:
A=[1 -9 8;3 4 6;1 5 0]#Definimos una matriz

3×3 Array{Int64,2}:
 1  -9  8
 3   4  6
 1   5  0

In [3]:
u=[1,4,9]#Definimos un vector

3-element Array{Int64,1}:
 1
 4
 9

In [4]:
matvec(A,u)#Comprobamos la función

[37.0, 73.0, 21.0]

In [5]:
function multimat(A,B)
    if size(A)[2]== size(B)[1]#Comparamos el tamaño de las matrices 
        k= zeros(size(A)[1],size(B)[2])#Creamos un contador para almacenar el mismo resultado 
        for i in 1:size(A)[1]#Iniciamos el  ciclo for 
            l=1 #Marcamos las columnas de B
            while l<=size(A)[1] #Mientras las columnas de B sean menor o iguales a los renglones de A
                m=0 #Abrimos un contador que almacena el resultado de n
                for j in 1:size(B)[1]#Para los renglones de b 
                    n=A[i,j]*B[j,l]#Multiplicamos i con cada j 
                    m+=n #Se suman los resultados de n
                end
                k[i,l]=m #m e s cada i*j
                l+=1 #Recorremos la matriz de 1 en 1 
            end
        end
        print(k) # Imprimimos el resultado 
    end
end

multimat (generic function with 1 method)

In [6]:
A= [1 8 5; 4 -4 5; 3 -2 7]#Creamos una matriz

3×3 Array{Int64,2}:
 1   8  5
 4  -4  5
 3  -2  7

In [7]:
B=[1 7 -4; 6 3 -1;  0 4 2]

3×3 Array{Int64,2}:
 1  7  -4
 6  3  -1
 0  4   2

In [8]:
multimat(A,B)#Comprobamos la función

[49.0 51.0 -2.0; -20.0 36.0 -2.0; -9.0 43.0 4.0]