In [1]:
function sum_mat2(A,B) 
    if size(A)==size(B)==(2,2)#Comparamos el tamaño de las matrices
        P=zeros(size(A))#Hacemos un contador para almacenar el resultado 
        for i in 1:size(A)[1] #Para cada elemento de los renglones de A
            for j in 1:size(A)[2] #Para cada elemento de las columnas de A
                c=A[i,j]+B[i,j] #Aquí se realiza la suma de matrices
                P[i,j]=c #Le asignamos los resultados en el contador  
            end
        end
        print(P) #Imprime los resultados
    end
end

sum_mat2 (generic function with 1 method)

In [2]:
A=[1 7;6 5;]#Generamos la matriz A

2×2 Array{Int64,2}:
 1  7
 6  5

In [3]:
B=[1 -5;-1 2;]#Generamos la matriz B

2×2 Array{Int64,2}:
  1  -5
 -1   2

In [4]:
suma_mat2(A,B)

LoadError: UndefVarError: suma_mat2 not defined

In [5]:
function sum_matn(A,B) 
    if size(A)==size(B)#Comparamos el tamaño de las matrices 
        p=zeros(size(A))#Definimos un contador que sea una matriz del tamaño de A
        for i in 1:size(A)[1] #Para cada elemento de los renglones de A
            for j in 1:size(A)[2]#Para cada elemento de las columnas de A
                c=A[i,j]+B[i,j] #A c le asignamos el resultado
                p[i,j]=c #Entra el resultado en el contador 
            end
        end
        print(p) #Imprimimos el resultado 
    end
end

sum_matn (generic function with 1 method)

In [6]:
C=[8 4 10 1;4 15 -1 1;-7 1 0 5]

3×4 Array{Int64,2}:
  8   4  10  1
  4  15  -1  1
 -7   1   0  5

In [7]:
D=[1 7 -4  0;8  4 -10 6;7 3 9 3]

3×4 Array{Int64,2}:
 1  7   -4  0
 8  4  -10  6
 7  3    9  3

In [8]:
sum_matn(C,D)

[9.0 11.0 6.0 1.0; 12.0 19.0 -11.0 7.0; 0.0 4.0 9.0 8.0]