### Martínez Ibarra Hugo
***
### Computación <p style="text-align:right">Grupo 8381
## <p style="color:darkblue;text-align:center">Ejercicio #7

a) Escribe un programa que sume dos vectores en $\mathbb{R}³$, el usuario debe insertar las entradas de los vectores.

Recordar que la suma de vectores se hace entrada a entrada:
$$a=[a_{1,1}\quad a_{1,2}\quad a_{1,3}]$$
$$b=[b_{1,1}\quad b_{1,2}\quad b_{1,3}]$$
$$a+b=[a_{1,1}+b_{1,1}\quad a_{1,2}+b_{1,2}\quad a_{1,3}+b_{1,3}]$$

Para el caso de vectores verticales (columna):

$$a=\begin{bmatrix}a_{1,1}\\a_{2,1}\\a_{3,1}\end{bmatrix}\qquad b=\begin{bmatrix}b_{1,1}\\b_{2,1}\\b_{3,1}\end{bmatrix}$$
$$a+b=\begin{bmatrix}a_{1,1}+b_{1,1}\\a_{2,1}+b_{2,1}\\a_{3,1}+b_{3,1}\end{bmatrix}$$

In [1]:
#Aquí el usuario introduce las entradas de cada vector que se va a sumar.
#Sólo vectores horizontales (renglón).
a=[1 2 3]
b=[4 5 6];

In [2]:
#Se define la función para la suma en R³. Este algoritmo sirve para vectores verticales u horizontales.
#Se utiliza condicional para ver si se trata de un vector vertical u horizontal. Lo primero se corrobora al ver si son de la misma dimensión (1 para vectores verticales, 2 para vectores horizontales), luego si tienen el mismo número fe renglones, con lenght(), si coinciden en número de elementos se lleva a cabo la operación. Para el caso de vectores horizontales la dimensión de ambos vectores debe ser 2 y si tienen el mismo tamaño, size()=(1,3), se lleva a cabo la operación. Para ambos casos si no se cumple la condición principal se avisa que no son del mismo tamaño.
function sumr3(a::Array,b::Array)
    if ndims(a)==ndims(b) && ndims(a)==1
        if length(a)==length(b)
            sum=[a[1,]+b[1,],a[2,]+b[2,],a[3,]+b[3,]]
        else
            "No son del mismo tamaño"
        end
    elseif ndims(a)==2 && ndims(a)==ndims(b)
        if size(a)==size(b)&&size(a)==(1,3)
            sum=[a[1,1]+b[1,1] a[1,2]+b[1,2] a[1,3]+b[1,3]]
        else
            "No son del mismo tamaño o no son vectores renglón"
        end
    else
        "No definido"
    end
end

sumr3 (generic function with 1 method)

In [3]:
#Se prueba el algoritmo.
sumr3(a,b)

1×3 Array{Int64,2}:
 5  7  9

b) Escribe un programa que sume dos vectores en $\mathbb{R}^n$ las entradas de los vectores deben leerse de un archivo de datos. (recuerda que esto solo tiene sentido si los vectores a sumar son de la misma dimensión).

Recordar que la suma de vectores se hace entrada a entrada:
$$a=[a_{1,1}\quad a_{1,2}\quad\cdots\qquad a_{1,n}]$$
$$b=[b_{1,1}\quad b_{1,2}\quad\cdots\qquad b_{1,n}]$$
$$a+b=[a_{1,1}+b_{1,1}\quad a_{1,2}+b_{1,2}\quad\cdots\qquad a_{1,n}+b_{1,n}]$$

Para el caso de vectores verticales (columna):

$$a=\begin{bmatrix}a_{1,1}\\a_{2,1}\\\vdots\\a_{n,1}\end{bmatrix}\qquad b=\begin{bmatrix}b_{1,1}\\b_{2,1}\\\vdots\\b_{n,1}\end{bmatrix}$$
$$a+b=\begin{bmatrix}a_{1,1}+b_{1,1}\\a_{2,1}+b_{2,1}\\\vdots\\a_{n,1}+b_{n,1}\end{bmatrix}$$

In [4]:
#Se definen aquí los vectores para que luego sean escritos en un archivo, este paso sólo se hace con el propósito de que el archivo de datos se genere al mismo tiempo que se corre este cuaderno, pues de lo contrario se tendría que subir un archivo de texto extra, además del presente cuaderno. Sólo por cuestión de practicidad, pero el programa hace precisamente lo que se pide.
va=[1 2 3 0]
vb=[4 5 6 0];

In [5]:
#Se escriben los archivos que contienen las entradas de los vectores, cabe mencionar que aquí depende cómo se escriban los vectores, verticales u horizontales, pue sasí los leerá el comando, por eso se debe ser cuidadoso con la colocación del símbolo separador("|").
writedlm("a.txt",va,'|')
writedlm("b.txt",vb,'|')

In [6]:
#Se leen los datos provenientes de los archivos.
a=readdlm("a.txt",'|')
b=readdlm("b.txt",'|');

In [7]:
a

1×4 Array{Float64,2}:
 1.0  2.0  3.0  0.0

In [8]:
b

1×4 Array{Float64,2}:
 4.0  5.0  6.0  0.0

In [9]:
#Método1: Una función que recibe como argumento los dos vectores a sumar, sean horizontales (renglón) o verticales (columna).
#Dentro se divide en casos la forma de tomar y operar las entradas de los vectores. El primer caso es cuando los dos vectores son del mismo tamaño y además se trata de vectores columna, size(a)[2]=1 que indica que el número de columnas es 1, después se crea un vector de ceros con las dimensiones (tamaño) de cualquiera de los vectores inciaies, aquí se elige el vector a. La forma de llenarlo es con un ciclo for donde se mantiene constante el índice que representa la única columna existente y el contador sólo actua sobre el otro índice (de los renglones) donde llena cada entrada con la correspondiente suma.
#De manera similar se plantea el otro caso, con elseif, cuando ambos vectores tienen el mismo tamaño pero se trata de vectores renglón, y aquí al momento de llenar con el ciclo for se mantiene constante el índice que representa al único renglón existente y el contador actúa sobre el índice que representa las columnas.
#Como caso adicional se verifica cuando los vectores no tienen el mismo tamaño.
function sumnvect1(a::Array,b::Array)
    if size(a)==size(b) && size(a)[2]==1
        sumn=zeros(size(a)[1],size(a)[2])
        for i in 1:size(a)[1]
            sumn[i,size(a)[2]]=a[i,size(a)[2]]+b[i,size(b)[2]]
        end
        sumn
    elseif size(a)==size(b) && size(a)[1]==1
        sumn=zeros(size(a)[1],size(a)[2])
        for i in 1:size(a)[2]
            sumn[size(a)[1],i]=a[size(a)[1],i]+b[size(b)[1],i]
        end
        sumn
    else
        "No son del mismo tamaño"
    end
end

sumnvect1 (generic function with 1 method)

In [10]:
#Se prueba el algoritmo.
sumnvect1(a,b)

1×4 Array{Float64,2}:
 5.0  7.0  9.0  0.0

In [11]:
#Método2: Una función que contiene la función push! recibe como argumento los dos vectores a sumar, sean horizontales (renglón) o verticales (columna).
#El algoritmo es bastante similar al anterior, sólo que aquí luego de confirmar que son del mismo tamaño se crea un arreglo vació el cual se llenará con la función push del mismo modo que en el método pasado. Sólo para el caso de vectores renglón se debe volver a asignar al vector resultante el tamaño adecuado de acuerdo a los vectores de los que proviene, pues la función push llena el arreglo, por defecto, como un vector columna.
function sumnvect2(a::Array,b::Array)
   if size(a)==size(b) && size(a)[2]==1
        sumn=[]
        for i in 1:size(a)[1]
            push!(sumn,a[i,size(a)[2]]+b[i,size(b)[2]])
        end
        sumn
    elseif size(a)==size(b) && size(a)[1]==1
        sumn=[]
        for i in 1:size(a)[2]
            push!(sumn,a[size(a)[1],i]+b[size(b)[1],i])
        end
        reshape(sumn,(size(a)[1],size(a)[2]))
    else
        "No son del mismo tamaño"
    end
end

sumnvect2 (generic function with 1 method)

In [12]:
#Se prueba el algoritmo.
sumnvect2(a,b)

1×4 Array{Any,2}:
 5.0  7.0  9.0  0.0