### Martínez Ibarra Hugo
***
### Computación <p style="text-align:right">Grupo 8381

## <p style="color:darkblue;text-align:center">Ejercicio de miércoles 8/11/2017

In [1]:
x=collect(0.0:1.0:10.0);
y=zeros(x);
m=2.0;
b=1.0;
for i in eachindex(x)
    y[i]=m*x[i]+b
end

In [2]:
T1=["x"]
T2=["y=f(x)"]
T=hcat(T1,T2)

1×2 Array{String,2}:
 "x"  "y=f(x)"

In [3]:
Tabla0=hcat(x,y)

11×2 Array{Float64,2}:
  0.0   1.0
  1.0   3.0
  2.0   5.0
  3.0   7.0
  4.0   9.0
  5.0  11.0
  6.0  13.0
  7.0  15.0
  8.0  17.0
  9.0  19.0
 10.0  21.0

In [4]:
Tabla=vcat(T,Tabla0)

12×2 Array{Any,2}:
   "x"    "y=f(x)"
  0.0    1.0      
  1.0    3.0      
  2.0    5.0      
  3.0    7.0      
  4.0    9.0      
  5.0   11.0      
  6.0   13.0      
  7.0   15.0      
  8.0   17.0      
  9.0   19.0      
 10.0   21.0      

In [5]:
writedlm("ValoresY.txt",Tabla,'|')

In [6]:
;cat ValoresY.txt

x|y=f(x)
0|1
1|3
2|5
3|7
4|9
5|11
6|13
7|15
8|17
9|19
10|21


In [7]:
using Plots
gr()

Plots.GRBackend()

In [8]:
plot(x,y,w=2,label=["y=f(x)"],lcolor=:green)
title!("Ecuación de una recta")
xaxis!("x")
yaxis!("y")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 8 
 
 
 10 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 Ecuación de una recta 
 
 
 x 
 
 
 y 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y=f(x)

In [9]:
using Interact

In [10]:
@manipulate for m=0.0:1.0:4.0, b=0.0:1.0:4.0
    y=m.*x.+b
    plot(x,y,w=2,xlim=(minimum(x),maximum(x)),ylim=(minimum(y),maximum(y)),label=["y=f(x)"],lcolor=:darkblue)
    title!("Ecuación de una recta")
    xaxis!("x")
    yaxis!("y")
end

Interact.Options{:SelectionSlider,Any}(1: "input" = 2.0 Any , "m", 2.0, "2.0", 3, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("0.0"=>0.0,"1.0"=>1.0,"2.0"=>2.0,"3.0"=>3.0,"4.0"=>4.0), Dict{Any,Any}(Pair{Any,Any}(0.0, "0.0"),Pair{Any,Any}(4.0, "4.0"),Pair{Any,Any}(2.0, "2.0"),Pair{Any,Any}(3.0, "3.0"),Pair{Any,Any}(1.0, "1.0"))), Any[], Any[], true, "horizontal")

Interact.Options{:SelectionSlider,Any}(3: "input-2" = 2.0 Any , "b", 2.0, "2.0", 3, Interact.OptionDict(DataStructures.OrderedDict{Any,Any}("0.0"=>0.0,"1.0"=>1.0,"2.0"=>2.0,"3.0"=>3.0,"4.0"=>4.0), Dict{Any,Any}(Pair{Any,Any}(0.0, "0.0"),Pair{Any,Any}(4.0, "4.0"),Pair{Any,Any}(2.0, "2.0"),Pair{Any,Any}(3.0, "3.0"),Pair{Any,Any}(1.0, "1.0"))), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 8 
 
 
 10 
 
 
 5 
 
 
 10 
 
 
 15 
 
 
 20 
 
 
 Ecuación de una recta 
 
 
 x 
 
 
 y 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y=f(x)