### Martínez Ibarra Hugo
***
### Computación <p style="text-align:right">Grupo 8381
## <p style="color:darkblue;text-align:center">Ejercicio #9

a) Sumar dos matrices en $\mathbb{R}^{2x2}$, el usuario debe insertar las entradas de las matrices.

Recordar que la suma de matrices se hace entrada a entrada y con matrices del mismo tamaño:
$$A_{2x2}=\begin{bmatrix}a_{1,1}&a_{1,2}\\a_{2,1}&a_{2,1}\end{bmatrix}$$
$$B_{2x2}=\begin{bmatrix}b_{1,1}&b_{1,2}\\b_{2,1}&b_{2,1}\end{bmatrix}$$
$$A+B=\begin{bmatrix}a_{1,1}+b_{1,1}&a_{1,2}+b_{1,2}\\a_{2,1}+b_{2,1}&a_{2,2}+b_{2,2}\end{bmatrix}$$

In [1]:
#Aquí el usuario debe introducir las entradas de las matrices de 2x2.
A=[1 2;3 4]
B=[5 6;7 8]

2×2 Array{Int64,2}:
 5  6
 7  8

In [2]:
#Se define una función para la suma de matrices de 2x2, por lo que recibe como entradas dos matrices de 2x2.
#Dentro se comienza por corroborar que ambas matrices sean del mismo tamño, si esto sucede se crea una matriz del mismo tamaño que cualquiera de las dos; 2x2, pero llena de ceros, los cuales se remplazarán eventualmente por los valores de la suma. Después se emplea la idea de suma de vectores de un ejercicio pasado, donde se hace la suma de vectores columna, pues aquí con un ciclo se llena la primera columna de la matriz resultante (r) y con otro ciclo for la otra columna de dicha matirz.
#Adicionalmente se añade una advertencia cuando no se cumple la igualdad de tamaño de las matrices de entrada.
function summatr22(A::Array,B::Array)
    if size(A)==size(B)
        sum=zeros(2,2)
        for i in 1:2
            sum[i,1]=A[i,1]+B[i,1]
        end
        for i in 1:2
            sum[i,2]=A[i,2]+B[i,2]
        end
        sum
    else
        "No se trata de matrices de 2x2"
    end
end        

summatr22 (generic function with 1 method)

In [3]:
#Se prueba el algoritmo.
summatr22(A,B)

2×2 Array{Float64,2}:
  6.0   8.0
 10.0  12.0

b) Escribe un programa que sume dos matrices en $\mathbb{R}^{nxn}$, las entradas de las matrices deben leerse de un archivo. Recuerda también que esto solo tiene sentido si las matrices a sumar son de la misma dimensión.

$$A_{nxn}= 
 \begin{bmatrix}
  a_{1,1}&a_{1,2}&\cdots&a_{1,n}\\
  a_{2,1}&a_{2,2}&\cdots&a_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{n,1}&a_{n,2}&\cdots&a_{n,n} 
    \end{bmatrix}\qquad B_{nxn}= 
 \begin{bmatrix}
  b_{1,1}&b_{1,2}&\cdots&b_{1,n}\\
  b_{2,1}&b_{2,2}&\cdots&b_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  b_{n,1}&b_{n,2}&\cdots&b_{n,n} 
\end{bmatrix}$$

$$\begin{bmatrix}
  a_{1,1}&a_{1,2}&\cdots&a_{1,n}\\
  a_{2,1}&a_{2,2}&\cdots&a_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{n,1}&a_{n,2}&\cdots&a_{n,n} 
    \end{bmatrix}
  \begin{bmatrix}
  b_{1,1}&b_{1,2}&\cdots&b_{1,n}\\
  b_{2,1}&b_{2,2}&\cdots&b_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  b_{n,1}&b_{n,2}&\cdots&b_{n,n} 
  \end{bmatrix}=
  \begin{bmatrix}
  a_{1,1}+b_{1,1}&a_{1,2}+b_{1,2}&\cdots&a_{1,n}+b_{1,n}\\
  a_{2,1}+b_{2,1}&a_{2,2}+b_{2,2}&\cdots&a_{2,n}+b_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{n,1}+b_{n,1}&a_{n,2}+b_{n,2}&\cdots&a_{n,n}+b_{n,n}
  \end{bmatrix}=C_{nxn}$$

In [4]:
#Se definen aquí los vectores para que luego sean escritos en un archivo, este paso sólo se hace con el propósito de que el archivo de datos se genere al mismo tiempo que se corre este cuaderno, pues de lo contrario se tendría que subir un archivo de texto extra, además del presente cuaderno. Sólo por cuestión de practicidad, pero el programa hace precisamente lo que se pide.
MA=[1 2 0;3 4 0;0 0 0]
MB=[5 6 0;7 8 0;0 0 0];

In [5]:
#Se escriben los archivos que contienen las entradas de los vectores, cabe mencionar que aquí depende cómo se escriban los vectores, verticales u horizontales, pue sasí los leerá el comando, por eso se debe ser cuidadoso con la colocación del símbolo separador("|").
writedlm("a.txt",MA,'|')
writedlm("b.txt",MB,'|')

In [6]:
#Se leen los datos provenientes de los archivos.
A=readdlm("a.txt",'|')
B=readdlm("b.txt",'|');

In [7]:
A

3×3 Array{Float64,2}:
 1.0  2.0  0.0
 3.0  4.0  0.0
 0.0  0.0  0.0

In [8]:
B

3×3 Array{Float64,2}:
 5.0  6.0  0.0
 7.0  8.0  0.0
 0.0  0.0  0.0

In [9]:
#Se define una función que tendrá como entrada dos matrices.
#Dentro se comienza por corroborar que las dos matrices de entrada sean del mismo tamaño nxn. Si esto sucede se crea una matriz de ceros del tamaño de cualquiera de las dos matrices de entrada (r),aquí se elige a. Luego con un ciclo for que recorre los índices de los renglones de la matriz resultante (r) y dentro otro ciclo for que va a recorrer las columnas de la misma matriz, aquí se pretende que por cada renglón de r que se recorre, se recorrerán todas las columnas de r, y como se trata de matrices de nxn, la suma el simplemente sumar las entradas correspondientes de cada matriz de entrada en la matriz resultante; es decir coinciden los ínidices de las entrada.
#Adicionalmente se añade una advertencia cuando las matrices de entrada no son del mismo tamaño.
function summat(A::Array,B::Array)
    if size(A)==size(B)
        sum=zeros(size(A)[1],size(A)[2])
        for i in 1:size(A)[1]
            for j in 1:size(A)[2]
                sum[i,j]=A[i,j]+B[i,j]
            end
        end
        sum
    else
        "No son del mismo tamaño"
    end
end
        

summat (generic function with 1 method)

In [10]:
#Se prueba el algoritmo.
summat(A,B)

3×3 Array{Float64,2}:
  6.0   8.0  0.0
 10.0  12.0  0.0
  0.0   0.0  0.0