### Martínez Ibarra Hugo
***
### Computación <p style="text-align:right">Grupo 8381
## <p style="color:darkblue;text-align:center">Ejercicio #10

a) Escribe un programa que realice el producto de una matriz en $\mathbb{R}^{mxn}$ por un vector en $\mathbb{R}^n$ las entradas tanto del vector como de la matriz deben leerse de un archivo. (para facilitarte las cosas puedes convertir tu programa de producto punto “del ejercicio 8” en una función)

La representación de la operación anterior es la siguiente:
Recordar que para la multiplicación de una matriz por un vector, el cual es un caso particular de una multiplicación de matrices, pues es una matriz por otra matriz de una sola columna; se debe cumplir que el número de columnas de la matriz sea igual al número de renglones del vector, y el orden orden en que se hace la multiplicación es importante. 
$$A_{mxn}= 
 \begin{bmatrix}
  a_{1,1}&a_{1,2}&\cdots&a_{1,n}\\
  a_{2,1}&a_{2,2}&\cdots&a_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{m,1}&a_{m,2}&\cdots&a_{m,n} 
 \end{bmatrix} b_{nx1}=\begin{bmatrix}b_{1,1}\\b_{2,1}\\ \vdots\\b_{n,1}\end{bmatrix}$$
$$\begin{bmatrix}
  a_{1,1}&a_{1,2}&\cdots&a_{1,n}\\
  a_{2,1}&a_{2,2}&\cdots&a_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{m,1}&a_{m,2}&\cdots&a_{m,n} 
 \end{bmatrix}\begin{bmatrix}b_{1,1}\\b_{2,1}\\ \vdots\\b_{n,1}\end{bmatrix}=\begin{bmatrix}a_{1,1}b_{1,1}+a_{1,2}b_{2,1}+\cdots+a_{1,n}b_{n,1}\\a_{2,1}b_{1,1}+a_{2,2}b_{2,1}+\cdots+a_{2,n}b_{n,1}\\ \vdots\\a_{m,1}b_{1,1}+a_{m,2}b_{2,1}+\cdots+a_{m,n}b_{n,1}\end{bmatrix}=c_{mx1}$$

In [1]:
#Se definen aquí los vectores para que luego sean escritos en un archivo, este paso sólo se hace con el propósito de que el archivo de datos se genere al mismo tiempo que se corre este cuaderno, pues de lo contrario se tendría que subir un archivo de texto extra, además del presente cuaderno. Sólo por cuestión de practicidad, pero el programa hace precisamente lo que se pide.
A=[1 2 3;4 5 6]
b=[7,8,9];

In [2]:
#Se escriben los archivos que contienen las entradas de los vectores, cabe mencionar que aquí depende cómo se escriban los vectores, verticales u horizontales, pue sasí los leerá el comando, por eso se debe ser cuidadoso con la colocación del símbolo separador("|").
writedlm("A.txt",A,'|')
writedlm("b.txt",b,'|')

In [3]:
#Se leen los datos provenientes de los archivos.
A=readdlm("A.txt",'|')
b=readdlm("b.txt",'|');

In [4]:
A

2×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [5]:
b

3×1 Array{Float64,2}:
 7.0
 8.0
 9.0

In [6]:
#Se retoma la función que efectúa el producto escalar.
function prodesc(a::Array,b::Array)
    if size(a)==size(b)
        R=zeros(a)
        for i in eachindex(R)
            R[i]=a[i]*b[i]
        end
        sum(R)
    elseif size(a)[1]==size(b)[2] && size(a)[2]==size(b)[1]
        R=zeros(a)
        for i in eachindex(R)
            R[i]=a[i]*b[i]
        end
        sum(R)
    else
        print("El tamaño de los vectores no es compatible")
    end
end

prodesc (generic function with 1 method)

In [7]:
#Se define la función de multiplicación de una matriz por un vector (en ese orden estristamente); una matriz de mxn y un vector de nx1 para que sean de tamaño compatible.
#Dentro se comienza por corroborar la compatibilidad de tamaño; es decir, que el número de columnas de la matriz sea igual al número de renglones del vector vertical (columna). Luego se crea un arreglo de ceros (R), especificamente un vector que tienes de tamaño: el mismo número de renglones que la matriz y el mismo núemro de columnas que el vector;es decir 1. Después se llena el vector R con un ciclo for, mediante el uso de la función prodesc() (creada en un ejercicio anterior), el producto escalar se realiza entre cada renglón de la matriz de entrada con la única columna del vector de entrada. Para indicar el renglón de una matriz se expresa como A[i,:] donde i es el número de renglón deseado y : hace referencia a todos los elementos en ese índice (renglón).
#Adicionalmente se incluye una advertencia cuando exista el caso de que el tamño de la matriz y el vector no son compatibles.
function multmatvect(A::Array,b::Array)
    if size(A)[2]==size(b)[1]
        R=zeros(size(A)[1],size(b)[2])
        for i in 1:size(A)[1]
            R[i,size(b)[2]]=prodesc(A[i,:],b[:,size(b)[2]])
        end
        R
    else
        print("No son de tamaño compatible")
    end
end

multmatvect (generic function with 1 method)

In [8]:
#Se prueba el algoritmo.
multmatvect(A,b)

2×1 Array{Float64,2}:
  50.0
 122.0

b) Escribe un programa que realice el producto de dos matrices, una en $\mathbb{R}^{mxn}$ y otra en $\mathbb{R}^{nxp}$, el usuario debe insertar las entradas de las matrices. Apóyate en tu programa anterior, pues es una generalización de este.
NOTA: En general, por convención cuando se multiplica una matriz por un vector se pone la matriz del lado izquierdo y el vector del lado derecho; y este a su vez se considera un vector columna.

Recordar que es importante que en la mutiplicación de matrices, para que esta sea posible, el número de columnas de la primera matriz debe ser igual al número de renglones de la segunda matriz, estrcitamente en ese orden para que la multiplicación esté definida. En este caso se puede representar de la siguiente forma.

$$A_{mxn}= 
 \begin{bmatrix}
  a_{1,1}&a_{1,2}&\cdots&a_{1,n}\\
  a_{2,1}&a_{2,2}&\cdots&a_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{m,1}&a_{m,2}&\cdots&a_{m,n} 
 \end{bmatrix}
 B_{nxp}= 
 \begin{bmatrix}
  b_{1,1}&b_{1,2}&\cdots&b_{1,p}\\
  b_{2,1}&b_{2,2}&\cdots&b_{2,p}\\
  \vdots&\vdots&\ddots&\vdots\\
  b_{n,1}&b_{n,2}&\cdots&a_{n,p} 
 \end{bmatrix}$$
 
 $$\begin{bmatrix}
  a_{1,1}&a_{1,2}&\cdots&a_{1,n}\\
  a_{2,1}&a_{2,2}&\cdots&a_{2,n}\\
  \vdots&\vdots&\ddots&\vdots\\
  a_{m,1}&a_{m,2}&\cdots&a_{m,n} 
 \end{bmatrix}
 \begin{bmatrix}
  b_{1,1}&b_{1,2}&\cdots&b_{1,p}\\
  b_{2,1}&b_{2,2}&\cdots&b_{2,p}\\
  \vdots&\vdots&\ddots&\vdots\\
  b_{n,1}&b_{n,2}&\cdots&a_{n,p} 
 \end{bmatrix}=
 \begin{bmatrix}
  A_{1\,n}\bullet B_{n\,1}&A_{1\,n}\bullet B_{n\,2}&\cdots&A_{1\,n}\bullet B_{n\,p}\\
  A_{2\,n}\bullet B_{n\,1}&A_{2\,n}\bullet B_{n\,2}&\cdots&A_{2\,n}\bullet B_{n\,p}\\
  \vdots&\vdots&\ddots&\vdots\\
  A_{m\,n}\bullet B_{n\,1}&A_{m\,n}\bullet B_{n\,2}&\cdots&A_{m\,n}\bullet B_{n\,p} 
 \end{bmatrix}$$
 
 Donde la notación $A_{r\,s}$ se refiere a la tupla que corresponde al renglón r y la columna s y $A_{r\,s}\bullet B_{s\,t}$ el producto punto entre dos tuplas.
 

In [9]:
#Se definen aquí los vectores para que luego sean escritos en un archivo, este paso sólo se hace con el propósito de que el archivo de datos se genere al mismo tiempo que se corre este cuaderno, pues de lo contrario se tendría que subir un archivo de texto extra, además del presente cuaderno. Sólo por cuestión de practicidad, pero el programa hace precisamente lo que se pide.
MA=[5.0 8.0 6.0;9.0 3.0 2.0];
MB=[7.0 2.0 1.0;5.0 4.0 1.0;2.0 6.0 1.0];

In [10]:
#Se escriben los archivos que contienen las entradas de los vectores, cabe mencionar que aquí depende cómo se escriban los vectores, verticales u horizontales, pue sasí los leerá el comando, por eso se debe ser cuidadoso con la colocación del símbolo separador("|").
writedlm("A.txt",MA,'|')
writedlm("B.txt",MB,'|')

In [11]:
#Se leen los datos provenientes de los archivos.
A=readdlm("A.txt",'|')
B=readdlm("b.txt",'|');

In [12]:
A

2×3 Array{Float64,2}:
 5.0  8.0  6.0
 9.0  3.0  2.0

In [13]:
B

3×3 Array{Float64,2}:
 7.0  2.0  1.0
 5.0  4.0  1.0
 2.0  6.0  1.0

In [14]:
#Se define la función para la multiplicación de matrices.
#Dentro se comienza por corroborar que los tamaños de las matrices son compatibles; esto es, la primera matriz debe tener el mismo número de columnas que el número de renglones de la segunda matriz. Si esto se cumple, se crea una matriz de ceros (R) que tiene el mismo número de renglones que la primera matriz y el mismo número de columnas que la segunda matriz. Después se llena el vector R con un ciclo for, mediante el uso de la función prodesc() (creada en un ejercicio anterior), el producto escalar se realiza entre cada renglón de la primera matriz de entrada con cada columna de la segunda matriz de entrada. Para indicar el renglón de la primera matriz se expresa como A[i,:] donde i es el número de renglón deseado y ":" hace referencia a todos los elementos en ese índice (renglón). Mientras que B[:,j] se refiere a la columna j de la segunda matriz.
#Adicionalmente se incluye una advertencia cuando exista el caso de que el tamño de la matriz y el vector no son compatibles.
function multmat(A::Array,B::Array)
    if size(A)[2]==size(B)[1]
        R=zeros(size(A)[1],size(B)[2])
        for i in 1:size(A)[1]
            for j in 1:size(B)[2]
                R[i,j]=prodesc(A[i,:],B[:,j])
            end
        end
        R
    else
        print("No son de tamaño compatible")
    end
end

multmat (generic function with 1 method)

In [15]:
#Se prueba el algoritmo.
multmat(A,B)

2×3 Array{Float64,2}:
 87.0  78.0  19.0
 82.0  42.0  14.0