### Martínez Ibarra Hugo
***
### Computación <p style="text-align:right">Grupo 8381

## <p style="color:darkblue;text-align:center">Tarea de lunes 27/11/2017
### Producto escalar o interior y multiplicación de matrices a partir de la lectura de un archivo de  texto

In [1]:
MA=[5.0 8.0 6.0;9.0 3.0 2.0];
MB=[7.0,5.0,2.0];

In [2]:
writedlm("A.txt",MA,'|')
writedlm("B.txt",MB,'|');

In [3]:
A=readdlm("A.txt",'|')
#Se asigna un nombre al resultado de leer el archivo que contiene los datos que serán las entradas de la matriz.

2×3 Array{Float64,2}:
 5.0  8.0  6.0
 9.0  3.0  2.0

In [4]:
B=readdlm("B.txt",'|')
#Se asigna un nombre al resultado de leer el archivo que contiene los datos que serán las entradas de la matriz.

3×1 Array{Float64,2}:
 7.0
 5.0
 2.0

In [5]:
size(A)

(2, 3)

In [6]:
size(B)

(3, 1)

In [7]:
C=zeros(size(A)[1],size(B)[2])
#Ejemplo de cómo será eñ tamaño de la matriz resultante, este se definirá de neuvo más adelante en la función de multiplicación de matrices
# Se acaba de definir el tamaño de la matriz que contendrá el resultado de la multiplicación de matrices.
# Al escribir size()[]Dentro de los corchetes se indica el índice del vector (dupla) "size" que define el tamaño de la matrix.

2×1 Array{Float64,2}:
 0.0
 0.0

In [8]:
D=[1,2,3] #Vector ejemplo creado para verificar función de producto escalar.

3-element Array{Int64,1}:
 1
 2
 3

In [9]:
E=[4,5,6] #Vector ejemplo creado para verificar función de producto escalar.

3-element Array{Int64,1}:
 4
 5
 6

In [10]:
#Definición  de la función producto escalar
function prodesc(M1::Array,M2::Array)
    if size(M1)==size(M2)
        R=zeros(M1)
        for i in eachindex(R)
            R[i]=M1[i]*M2[i]
        end
        sum(R)
    else
        print("No son del mismo tamaño")
    end
end

prodesc (generic function with 1 method)

In [11]:
prodesc(D,E) #Se está verificando la función escalar con los vectores ejemplo.

32

In [12]:
D[:,1] #Aquí se está llamando, en forma de vector, a todos los elementos de dimensión 1 del vector D; es decir a la columna 1.

3-element Array{Int64,1}:
 1
 2
 3

In [13]:
D[1,:] #Aquí se está llamando, en forma de vector, a todos los elementos del primer renglón, es decir de todas las dimensiones (o columnas).

1-element Array{Int64,1}:
 1

In [14]:
Ar1=A[1,:] #Se les puede asignar un nombre a los vectores que se obtuvieron de la forma anterior. Esto es un ejemplo con el primer renglón de la matriz A que corresponde a el problema original.

3-element Array{Float64,1}:
 5.0
 8.0
 6.0

In [15]:
Bc1=B[:,1] #Se les puede asignar un nombre a los vectores que se obtuvieron de la forma anterior. Esto es un ejemplo con la primer columna de la matriz B que corresponde a el problema original.

3-element Array{Float64,1}:
 7.0
 5.0
 2.0

Lo anterior es necesario, pues la multiplicación de matrices se hace entre un renglon de la primera matriz y una columna de la segunda matriz, pero además que el índice de la columna (en el renglón de la primera matriz) corresponda con el índice del renglón (de la columna de la segunda matriz).

In [16]:
prodesc(Ar1,Bc1) #Haciendo una prueba del producto escalar con el renglón 1 de la primera matriz (A) y la columna 1 de la segunda matriz (B).

87.0

In [17]:
prodesc(A[1,:],B[:,1]) #Se puede usar la función prodcuto escalar sin asignar un nombre a los vectores obtenidos.

87.0

In [18]:
#Función para definir cómo se va a llenar la matriz resultante de la multiplicación.
function multmat(M1::Array,M2::Array)
    if size(M1)[2]==size(M2)[1]
        R=zeros(size(M1)[1],size(M2)[2])
        for i in [1,size(M1)[1]]
            for j in [1,size(M2)[2]]
                R[i,j]=prodesc(M1[i,:],M2[:,j])
            end
        end
        R
    else
        print("No son del mismo tamaño")
    end
end

multmat (generic function with 1 method)

In [19]:
#Matriz resultado
AB=multmat(A,B)

2×1 Array{Float64,2}:
 87.0
 82.0